### ISSUE TITLE
Throws error when formatting "??="

### ISSUE THREAD

**Issue by freewind** [dprint/dprint-plugin-typescript#100]
**Describe the bug**

dprint-plugin-typescript version: 0.20.4

**Input Code**

```ts
a ??= {}
```

**Expected Output**

Not throw error

**Actual Output**

```
Line 56, column 33: Unexpected token Some(AssignOp("="))

  a ??= {};

```

**Comment by dsherret** [comment]
@freewind upgrade to 0.40.1 and it should work.
