### ISSUE TITLE
Throws error when formatting labeled tuple

### ISSUE THREAD

**Issue by freewind** [dprint/dprint-plugin-typescript#101]
**Describe the bug**

dprint-plugin-typescript version: 0.20.4

**Input Code**

```ts
type A = [name: string, value: string];
```

**Expected Output**

Not throw error

**Actual Output**

```ts
Expected Comma, got Some(Colon)

  value]: [name: string
               ~
```

**Comment by dsherret** [comment]
@freewind similarly, upgrade to 0.40.1 and it should work. Been a lot of development done since 0.20.4 :)

https://dprint.dev/playground/#code/C4TwDgpgBAglC8UDaA7AhgWwgLigZ2ACcBLFAcwBooA3NAGwFcd8jSyBdAbiA/language/typescript

**Comment by dsherret** [comment]
On a sidenote, I wish there were an easier way to automatically upgrade all plugins to the latest version in the CLI. I will be working on that in the future.
