### ISSUE TITLE
Comments are removed in files with shebangs and only comments

### ISSUE THREAD

**Issue by Liamolucko** [dprint/dprint-plugin-typescript#108]
**Describe the bug**
If a file has a shebang and nothing but comments, the comments will be removed.

dprint-plugin-typescript version: 0.40.1

**Input Code**

```ts
#!/foo/bar

// A comment
/* A block comment */
```

**Expected Output**

```ts
#!/foo/bar

// A comment
/* A block comment */

```

**Actual Output**

```ts
#!/foo/bar


```

**Comment by dsherret** [comment]
Fixed in https://github.com/dprint/dprint-plugin-typescript/commit/a0fce2c4e779f0bdb2ec4864bd8ab1c9454582f5

Forgot to tag it in the commit message.

**Comment by dsherret** [comment]
@Liamolucko thanks for this edge case and the good reproduction steps.
