### ISSUE TITLE
TypeScript: Comma as separator for single-line type literal

### ISSUE THREAD

**Issue by KSXGitHub** [dprint/dprint-plugin-typescript#11]
**Is your feature request related to a problem? Please describe.**

I want to write this code:

```typescript
type MyObject = { foo: number, bar: string }
```

But dprint-plugin-typescript converts it to semicolons:

```typescript
type MayObject = { foo: number; bar: string }
```

which it is not what I want.

**Describe the solution you'd like**

While I prefer commas as separator, others might prefer semicolons, so I suggest a configuration key should be introduced to specify whether the separator should be commas or semicolons:
* `objectLiteralTypeSeparator: 'comma' | 'semicolon'`
* `singleLineObjectLiteralTypeSeparator: 'comma' | 'semicolon''`
* `multiLineObjectLiteralTypeSeparator: 'comma' | 'semicolon' | 'none'`

**Describe alternatives you've considered**

**Additional context**

I have set `.semi_colons(SemiColons::Asi)` in [my own formatter](https://github.com/KSXGitHub/sane-fmt/blob/0.2.16/src/rules/mod.rs#L14), so I would prefer multi-line object literal type to **not** have separator.

**Comment by dsherret** [comment]
@KSXGitHub if you get the chance would you be able to check out the description on #40 and let me know if that looks good? Thanks! I believe it solves this issue.

Also, see this test:

https://github.com/dprint/dprint-plugin-typescript/pull/40/files#diff-f403c5f8b63b9b06fd9a0f5c0d028843
