### ISSUE TITLE
Incorrect placement of semicolon after call expression in expression statement

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#116]
**Describe the bug**

Deno version: 1.8.1

**Input Code**

```ts
a.b() //
```

**Expected Output**

```ts
a.b(); //
```

**Actual Output**

```ts
a.b() //
;
```

Ref: https://github.com/denoland/deno/issues/9809

**Comment by dsherret** [comment]
Caused by #106.
