### ISSUE TITLE
Formatting fails with private declare

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#128]
**Describe the bug**

dprint-plugin-typescript version: x.x.x

**Input Code**

```ts
class A {
  private declare() {}
}
```

**Expected Output**

```ts
class A {
  private declare() {}
}
```

**Actual Output**

```
Error formatting: ~/test.ts
   Line 2, column 18: Unexpected token `(`. Expected identifier, string literal, numeric literal or [ for the computed key
```

Ref: https://github.com/denoland/deno/issues/10548

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/1671
