### ISSUE TITLE
Option to disable `{ braceSpace }` in object literals

### ISSUE THREAD

**Issue by mitranim** [dprint/dprint-plugin-typescript#136]
Desired:

```js
void {one: 10, two: 20, three: 30}
```

Actual:

```js
void { one: 10, two: 20, three: 30 }
```

Not seeing a documented option to disable this additional spacing. If I missed one, then would appreciate a pointer, and a documentation update. Otherwise, would be nice to add an option. It would also be nice to get an option to consistently disable _all_ such brace spacing. Thanks!

**Comment by dsherret** [comment]
My bad and sorry about that! The JSON schema file was missing them. The configuration is `spaceSurroundingProperties: false` and there are AST node specific configuration for that as well. I've updated the JSON schema file so this should be resolved now:

https://dprint.dev/plugins/typescript/config/

**Comment by dsherret** [comment]
I think that doesn't disable this spacing for named imports and exports though. You might have to do:

```ts
"spaceSurroundingProperties": false,
"importDeclaration.spaceSurroundingNamedImports": false,
"exportDeclaration.spaceSurroundingNamedExports": false
```

**Comment by mitranim** [comment]
Works great. Thanks for the help! Appreciate the rapid response. 🙂
