### ISSUE TITLE
Configuration for using braces in a switch statement

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-typescript#163]
Some example code:

```ts
switch (test) {
    case 5: { return 5; }
    case 6: {
        return 6;
    }
    case 7:
        return 7;
}
```

This would tie into the "useBraces" configuration and could be turned off by setting `switchCase.useBraces` to false.

**Comment by Samuel-Therrien-Beslogic** [comment]
I think this would've re-implemented https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/switch-case-braces.md .

I guess a pure formatter (no static analysis) may not be able to know when it is safe to add/remove braces or not.
