### ISSUE TITLE
Maintain some spaces in JSX text

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-typescript#19]
Right now if there is some text like:

```ts
Testing <This />
```

Then it goes to format it like so:

```ts
Testing
<This />
```

This will be a bug because the space no longer exists—it's equivalent to `Testing<This />`.

Edit: Another scenario to ensure is handled is from #90 

```
function Test() {
    return <div>
        {foo} {bar}
    </div>;
}
```

**Comment by jeroenptrs** [comment]
Additional behaviour I've noticed is that formatting an unformatted (read: touched by prettier 😬 ) tsx file sometimes requires two passes. The following case is with `deno fmt`:

- This is the first format with `deno fmt`
![image](https://user-images.githubusercontent.com/19305608/94988644-0945a500-056f-11eb-8ab5-787c9e971a09.png)
- This is the second format with `deno fmt`
![image](https://user-images.githubusercontent.com/19305608/94988649-14003a00-056f-11eb-9e06-b64f75736bb0.png)

The file in question is this file:
https://github.com/denofn/denopack/blob/main/docs/src/pages/index.tsx

**Comment by thgh** [comment]
I'm still seeing the issue for this case in v0.38.5:
```
function Test() {
    return <div>
        {foo} {bar}
    </div>;
}
```

**Comment by dsherret** [comment]
@thgh fix will be in 0.39.0 (haven't released yet... still doing testing and finding some edge cases while trying it out on some code bases)

**Comment by thgh** [comment]
I just found some more inspiration on the [prettier tests](https://github.com/prettier/prettier/tree/main/tests/jsx), there seem to be some more cases that might produce invalid code.
* [tests/jsx/comments/eslint-disable.js](https://dprint.dev/playground/#code/MYewdgzgLgBATgUzAEwXGBeGBLKCC2EmAfDABQBQMMAPMtgG7EDeMA9AFQwIQA22YKAFp6EAIYAjXghgc2VajACQOPIQB0+MQAcyuAiRhgArr14BKBYvZce-QUKSTpsttYC+NNvSYVLQA/language/typescript)
* [tests/jsx/comments/in-end-tag.js](https://dprint.dev/playground/#code/PQKgBAvF0xYEYFMBmB7ATosBnANgQ2wAtJZYwRgAoAHnwD4bhgxcBLAO0SuAYG5aDJuHi5UAYwDWFar3oDajZq07dg8xcIRipMnhp7gy5fMgAuidDgLFSxqHrpKwy9lyr9Bz0NonTKHgY03ixu3BrBTC4iOv7UBj720GCmFlYc+AC2WEkOAU5M+C6hqlQRQrzRvroBBoZ29tXSuXD5FUU+on4yEd4x3ZQJRrlgmQCuuGZsAA64OSOOFSVcYACMPMtYAEw8ngWdsasyVV1SW3pyAvv9NSyupZdUmvcr6y-b+ldKN5JHlCexc4BdRfLSnOLFFTuEFAA/language/typescript) (very specific cases)
* [tests/jsx/spread/attribute.js](https://dprint.dev/playground/#code/PTAEHEHtIEwKADwwJYDdQG8B0OCGBfYAPgG45EV1scAKXUAHwc3wEp9RiyK1McsaAY0gA7GKAD8oAGbRQALlAAjXACd2nUuRCgAwpAC2BgKYiALqAORUx+El7Us9YACpQwo6YsvghLTypXd0MTc1AffgIucnsqSM5gD1CzOD9uWL48OFAEpK9U6IDMbNyQ-JzIgv8MjBA88xL4nXqUtLggA/language/typescript)

**Comment by dsherret** [comment]
@thgh thanks! I opeened #94. I believe most of these will be fixed in the next release, but look like some issues still remain.
