### ISSUE TITLE
Change enumDeclaration.memberSpacing to camelCase

### ISSUE THREAD

**Issue by Sonic12040** [dprint/dprint-plugin-typescript#26]
In other configuration options, like operatorPosition, nextControlFlowPosition, or singleBodyPosition, the configuration options are in camelCase, like nextLine, or sameLine.

In enumDeclaration.memberSpacing, it uses newline and blankline instead of newLine and blankLine. I would like to update this configuration option to more closely match the other options.

Note: This is found in lines 80-96 of types.rs

**Comment by dsherret** [comment]
Thanks a lot for pointing this out! I noticed something similar in another area yesterday and meant to do a search, but forgot.

**Comment by Sonic12040** [comment]
My pleasure! I noticed it while using the playground.

#27 - I went ahead and submitted this PR to resolve this particular issue. Note: This change in configuration would be breaking for users of the existing values.
