### ISSUE TITLE
[question] Force newline between functions/class block ?

### ISSUE THREAD

**Issue by lowlighter** [dprint/dprint-plugin-typescript#261]
So I may have missed it in https://dprint.dev/plugins/typescript/config/, but is it possible to keep a new line between `class` and `function` after opening brace (and eventually closing brace) like below ?

<table>
<tr>
<td>

```ts
class A {

    /** A constructor */
    constructor() {

    }

    /** Method */
    method() {
        
    }

}
```

</td>
<td>

```ts
class A {
    /** A constructor */
    constructor() {
    }

    /** Method */
    method() {
    }
}
```

</td>
</tr>
</table>

The left one is what I'd like to get while the right one is the dprint formatted one.

Anyway, thanks for your awesome lib 🙂

**Comment by dsherret** [comment]
I think this would be the "padding blocks" option discussed in #7

**Comment by lowlighter** [comment]
Indeed that looks like it!

Closing this as it seems to be a duplicate 👍
