### ISSUE TITLE
TSX: `Expected ,, got jsx name (c)`

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#264]
**Describe the bug**

Formatting errors with TSX containing `"\"` attribute value

dprint-plugin-typescript version: 0.51.0

**Input Code**

```ts
return (
        <>
          <A b="\" c="|"/>
          <A b="c"/>
        </>
  );
```

**Expected Output**

```ts
return (
    <>
        <A b="\" c="|" />
        <A b="c" />
    </>
);

```

**Actual Output**

```
Line 4, column 17: Expected ,, got jsx name (c)

            <A b="c"/>
                  ~
```

see https://dprint.dev/playground/#code/E4UwLgrsB2AEAUAoWLUoDwD5lt+ggrAEYC8ARADpmwDG5APmQPTa56Glk3OtuzoscASgDciREA/language/typescript

The issue seems to be `b="\"`.

**Comment by declanvong** [comment]
Same here -- looks like this one is also fixed now and can be closed, the playground link in the OP works successfully with 0.60.0.
