### ISSUE TITLE
inline type def with `false` const type is interpreted as code, not typing

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#266]
**Describe the bug**

an inline type def is interpreted not as type def but const

dprint-plugin-typescript version: 0.51.0

**Input Code**

```ts
Array(5).fill(0).map((_, i): ({ loading: false }) => ({
    loading: false,
}));
```

this transforms to JS
```js
Array(5).fill(0).map((_, i) => ({
    loading: false,
}));
```

Update: the problem here is actually the additional parens around the type, e.g.:

```ts
Array(5).fill(0).map((_, i): { loading: false } => ({
    loading: false,
}));
```
parses fine.

**Expected Output**

```ts
Array(5).fill(0).map((_, i): { loading: false } => ({
    loading: false,
}));
```

(superfluous parens removed)

**Actual Output**

```
Line 1, column 42: Expected ident

  (_, i): ({ loading: false }) => ({
                      ~~~~~
```

* dprint playground: https://dprint.dev/playground/#code/IIJxEME8AoFYEoB0AzAlgG3dADEgtuAA7TQD6ANAASrwBcl0A3pegPbgAmqAdgOb3Jw6AM4BTSgF94lALwA+BowBQlVS3Zc+AoWPJKp8ANxA/language/typescript
* ts playground: https://www.typescriptlang.org/play?#code/IIJxEME8AoFYEoB0AzAlgG3dADEgtuAA7TQD6ANAASrwBcl0A3pegPbgAmqAdgOb3Jw6AM4BTSgF94lALwA+BowBQlVS3Zc+AoWPJKp8ANxA

**Comment by declanvong** [comment]
Looks like this one is fixed now, the playground link in the OP works successfully with 0.60.0 😄
