### ISSUE TITLE
parens in function property fail to parse

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#268]
**Describe the bug**

parens in function property fail to parse.

dprint-plugin-typescript version: 0.51.0

**Input Code**

```ts
const x = {
prop: isCorrect
    ? fn => ({})
    : fn => true,
};
```

**Expected Output**

```ts
const x = {
    prop: isCorrect
        ? fn => ({})
        : fn => true,
};

```

(removing the additional `()` around the `{}` makes it parse)

**Actual Output**

```
Line 4, column 17: Expected :, got ,

      : fn => true,
                  ~
```

https://dprint.dev/playground/#code/MYewdgzgLgBAHjAvDA3gKAA4CcQYFwwCWEAwiFlgKbBRoz0wD8MAZmEgHwwAUKAvgEo6DAm04woWAK6UANGj4BuIA/language/typescript

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/2174

**Comment by joscha** [comment]
I just encountered another one of these:

```
    const wrappedApi: API<P> | undefined = api != null ? {
      process: async (params: Params): Promise<Response<P>> => {
        let response: Response<P>;
        return response;
      },
    } : undefined;
```
fails with:
```
Line 2, column 38: Expected =>, got :

  ync (params: Params): Promise<R
                      ~
```

see: https://dprint.dev/playground/#code/AQ4YwewOwZwF2AdwE4EMAO6CmATAgugJYBcweACgJIA85AfMAD7ACuUOWAZoVLsALzAMhYAEJBUFgBspwAPzAA3gChQodMghgsMGKVQwAnlDDAAFOlRoAtnuDkrqWwEpS5TdcIws1AEo70aG9aOgZ+BhU1NSksBGQAoKxSfxhA2B96AG5VKJB4uBZkKGB41MTs3IBfABockErgUjYObl4cTKA/language/typescript


Seems this was fixed in upstream in https://github.com/swc-project/swc/pull/2235 - can we pull in the new dependency?

**Comment by joscha** [comment]
actually, it might be a different bug - can you tell me how you created the repro for swc in https://github.com/swc-project/swc/issues/2174 please?

**Comment by dsherret** [comment]
It looks like that one was fixed in https://github.com/swc-project/swc/issues/2196
