### ISSUE TITLE
Alphabetical import order not maintained

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#270]
**Describe the bug**

`a` should come before `a/a`

dprint-plugin-typescript version: 0.51.0

**Input Code**

```ts
import { Observable, Subject, Subscription } from 'rxjs';
import { tap } from 'rxjs/operators';
```

**Expected Output**

```ts
import { Observable, Subject, Subscription } from 'rxjs';
import { tap } from 'rxjs/operators';
```

**Actual Output**

```ts
import { tap } from 'rxjs/operators';
import { Observable, Subject, Subscription } from 'rxjs';
```

Try it here: https://dprint.dev/playground/#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0wBo4BlAV1QCtMBjGMqjeqYMGYCAOzgF84AMygQQcAORQAHjXQSA3AChQkWIjgw8YAcNHips9AHoIYbHhjR5CoA/language/typescript

**Comment by dsherret** [comment]
The module specifiers were being sorted based on the folder paths similar to relative paths, however, unlike relative paths where the sort order can help visualize folder structure, the same doesn't really apply for absolute paths/package names/urls so it will just be straight alphabetical for non-relative module specifiers.

**Comment by joscha** [comment]
I think this is still broken for relative parent imports in `0.52.1`:

Code
```ts
import { _1 } from '../../a';
import { _2 } from '../../a/b';
import { _3 } from '../c';
import { _4 } from '../d/e';
import { _5 } from '../d/f';
```

results in:

```ts
import { _2 } from "../../a/b";
import { _1 } from "../../a";
import { _4 } from "../d/e";
import { _5 } from "../d/f";
import { _3 } from "../c";
```

see: https://dprint.dev/playground/#code/JYWwDg9gTgLgBAbzgfQIxwL5wGZQiOAcgDpiB6UsgQ0IG4AoUSWRFAJkxzwJPMqrIAjOo3DR4SZAGZOufEUoBjEU3GtkAFlncF5ACZkApirEtJAVm3zeZA9jpA/language/typescript

**Comment by joscha** [comment]
produced a test case here: https://github.com/dprint/dprint-plugin-typescript/pull/277
