### ISSUE TITLE
strings looking like comments repeat in JSX when inside tag

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#276]
**Describe the bug**

comment-like strings repeat

dprint-plugin-typescript version: 0.52.1

**Input Code**

```ts
export function install(/* ... */) {
    return (
        <Switch>
          // ...
        </Switch>
    );
}
```

**Expected Output**

same, one occurrence of `// ...`

**Actual Output**

```ts
export function install(/* ... */) {
    return (
        <Switch>
            // ... // ...
        </Switch>
    );
}
```

Try here: https://dprint.dev/playground/#code/KYDwDg9gTgLgBAMwK4DsDGMCWEV0ygZxgEMAbUgCgHoAqOAOkbhqoEo4BvAKDl7imAwkUXBR58JAHgDKAd0ww0ACwB84iRKpUGjdRslU5C5WomsA3FwC+QA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kAA4AnRCMTbIUyAEc2ijIgDKGAJ7REwyOIDuvWxwAiitvwdHySCQXABkERABpSidoEQDWTkQAIW1eAGNEdSgXLGoAOQsrBABzBzCkeKh+VIyABUUOWAxYVScOXhlEcsQAVXgHDg4ACV54YpLKyEaxhyTFNFt6xubWjRleBAwN+EmkAA8MJRptZQAxFRclppadjX2MbsmMVNg4MaUZdazIVWhbAFk2NBmo9jIpNAZeBhFNoritblB7qDAjo9AYRmMJvgxBJEMZUfptEUZl1wsIcZJArxtCcXKc2PA0vCAHSJWrU6jYTKZJzrTbbSb8BDU2wAUT2qMGN2Zb0QtQM4sljVWonElNYACsOHtmWYLNY7P4NASDN5fP5jFqdTIgSDwuzdGphM82HjAp0ZPwFRLdFLVDL7d6lTdyWq3aw7BCwpZUtBmVxNNSoTCovA0G1EHIlCodsZqGwZJ5EGloEmWR6vUTE2ksVA+TQBcYONXrGwaT40yVaicIdpmjz8C7w1BFPwNcWMIrfcr4PGW1Y2ycGWguz2DP2skOwWOJ+yMDHZ830q328vV+D17AB2At4FI6SY+I58eF6fO2Nuxe+1fN9pXcYhXgEUp0yGdnwyV8l3fYokiaFxYC4ABBNNEO0JosE6Zo0gAeV7ZNDEHP9h0gNJFE+TlumZEQYQgltEJEGMrFLDhcl-f9AlItQXSZGFwOSPQYTlDkaFY68KWIziOG46FtG4WwIT4+iYzyRAXAiRBbBcGF02xMNjEk6SimKICMDbRBFIYgwVLUjStO0HTVVxYw0EUZAsFeA0oUzTkLJjNyPPUzTtOdIi8wlGEMCLEsy2lI8IMXDsVzGPIOkQNBFQitjiOo7QAEl4BsLzOhoXyDFOFNbOCwj2NYHLsJEQrLGKjBSu0crtECuyHNvWqYUa7ySrixAlLKiqgvskKaqgHL+ua1qrEzBRlFULLjBEBkmRuKLS1SFkhqSATdAdTlRKycS1o2+EQL9Q8WwOnKhMdLkuDOvTAnWxkrp9UDYroyy2sum5Oqqxz1SgYpEAwRC0gyQZeP2w7HpO7lXqcwJYAarYmp8oaRrykRgYm6riNgGRNAi7aYv9IbIMSkoUs6NBcrJzLJuIq1RQcOaEYehbYnkFRpmKPhiiY3gWNDNHNW1a6ZyOLZwm0PjabPMZZZDXSpbrSGsHmPj7sE46RJRyWwamSHodhjh4buxGjeesS3ojXhightBuEzTRS0sfXEejSFoDZ4x72Q+ALChX7jwN3RsxVc673k4bBkvanbYe9WVR67J3IcWacb+vyc8iSqiZvUL0eMwSCioD5mo9g4nDQHRNgAWlgSvdEmduw90U4PNrzl64wRvm5oNuO8QFuRA8yAQAAXxAIA/language/typescript

**Comment by joscha** [comment]
slight possibility it is related to https://github.com/dprint/dprint-plugin-typescript/pull/263#issuecomment-908227784

**Comment by kavehsajjadi** [comment]
hahaha what a funny bug
**Input Code**
```
export function install(/* ... */) {
    return (
        <Switch>
          // ...
          // ...
          // ...
        </Switch>
    );
}
```

**Actual output**
```
export function install(/* ... */) {
    return (
        <Switch>
            // ... // ... // ... // ...
            // ...
            // ...
        </Switch>
    );
}

```

**Comment by joscha** [comment]
my hunch is that the comment is not marked as handled. The trace looks like this:

![Trace_-_should_keep_comments_as-is__trace_](https://user-images.githubusercontent.com/188038/133535405-2d915aac-155a-4f6d-a9ba-1fefb0005b00.png)

The marked part is where the whole of the comment is re-added a second time. Using breakpoints it doesn't seem to jump twice into that function though, so I am a bit unsure on where that ghost write comes from.

**Comment by joscha** [comment]
Found a potentially clearer test case:

```ts
export function install(/* ... */) {
    return (
        <Switch>
            // a
            // b
            // c
        </Switch>
    );
}
```

yields:

```ts
export function install(/* ... */) {
    return (
        <Switch>
            // a // b // c // a
            // b
            // c
        </Switch>
    );
}
```

**Comment by joscha** [comment]
Also seems like multiline is affected as well:

```ts
export function install(/* ... */) {
    return (
        <Switch>
            /* a */
            /* b */
            /* c */
        </Switch>
    );
}
```

which yields

```ts
export function install(/* ... */) {
    return (
        <Switch>
            /* a */ /* b */ /* c */ /* a */
            /* b */
            /* c */
        </Switch>
    );
}
```

**Comment by joscha** [comment]
Also interesting:

```
<A>
    /*
       a
       b
    */
</A>
```

seems the doubled comment actually gets collapsed and prepended:

```
<A>
    /* a b */ /*
       a
       b
    */
</A>;
```

the other examples made it look like its partially appended

**Comment by joscha** [comment]
I think the issue might not actually be only in the plugin, but coming from core: https://github.com/dprint/dprint/blob/3608bf73e477d1c87516e892d8c3b60aa1716e69/crates/core/src/formatting/parser_helpers/helpers.rs#L70 where the initial text of the group is added to the printed output due to `new_line_group`'s implementation.

**Comment by declanvong** [comment]
This might be an upstream bug. It looks like swc is returning `CommentLine` for those, when it shouldn't be as they're just text. Will verify tomorrow morning...

**Comment by dsherret** [comment]
> This might be an upstream bug. It looks like swc is returning `CommentLine` for those, when it shouldn't be as they're just text. Will verify tomorrow morning...

Yes, this is the bug. Sorry, I should have commented in here earlier. JSX comments look like `{/* comment */}`. I've opened https://github.com/swc-project/swc/issues/2264

**Comment by joscha** [comment]
Thanks guys! That explains why I am having such a hard time trying to fix this as my first bug, haha, @dsherret do you have a recommendation for one that would be a good starter?

**Comment by dsherret** [comment]
@joscha no sorry I don't have a good recommendation. I will try to add "good first issue" to something when I see it. Unfortunately a lot of these bugs are kind of hard ☹
