### ISSUE TITLE
discriminated union typedef is not formatted

### ISSUE THREAD

**Issue by joscha** [dprint/dprint-plugin-typescript#279]
**Describe the bug**

a discriminated union type def is not reformatted

dprint-plugin-typescript version: 0.52.1 and 0.51.0

**Input Code**

```ts
export type CommandOptions<T = DprintBinarySubCommand> =
    & GenericOptions<T>
    & (
        {
          command: 'fmt' | 'check',
          files?: readonly string[],
        } | { command: 'output-file-paths' | 'output-resolved-config' }
    );
```

**Expected Output**

```ts
export type CommandOptions<T = DprintBinarySubCommand> =
    & GenericOptions<T>
    & (
        | {
            command:
                | "fmt"
                | "check";
            files?: readonly string[];
        }
        | {
            command:
                | "output-file-paths"
                | "output-resolved-config";
        }
    );
```

**Actual Output**

```
export type CommandOptions<T = DprintBinarySubCommand> =
    & GenericOptions<T>
    & (
        {
            command: "fmt" | "check";
            files?: readonly string[];
        } | { command: "output-file-paths" | "output-resolved-config" }
    );
```

see https://dprint.dev/playground/#code/KYDwDg9gTgLgBDAnmYcDCEC2mCGA7AEwHkwYBLCPAZwB4AVOAXjgBEwoy8YAhTnKRAGUArgCMM2fAQB8TAFBxFcAGRwA4sDzAOAYxLlKtOtIVLVAClNKlAbyvWlOrLkIAuOAHIAZphge4AD6eOgAWwDoA1h4ANPYOcF5kADbAVAD87lDAOASUSYhwVDAceADmANoAurHxigC+gXA2cE6Sbp4QwjBgXQC0iSm9YDgwIVT+QR6d3X1ZVBBJAG7ABL1OeIml-nX2AJQA3EA/language/typescript

In fact, different input elicits different output each time:

```ts
export type CommandOptions<T = DprintBinarySubCommand> =
    & GenericOptions<T>
    & ({command: 'fmt' | 'check', files?: readonly string[] } | { command: 'output-file-paths' | 'output-resolved-config' });
```

for example is not reformatted to the above either, but kept almost as-is as well: https://dprint.dev/playground/#code/KYDwDg9gTgLgBDAnmYcDCEC2mCGA7AEwHkwYBLCPAZwB4AVOAXjgBEwoy8YAhTnKRAGUArgCMM2fAQB8TAFBxFcAGRwA4sDzAOAYxLlKtOtIVLVACgDeOrLkIAuOAHIAZphhO4AH2c6AFsA6ANZOADRwLmQANsBUAPyOUMA4BJRRiHBUMBx4AOYA2gC6cAC+3nCWcDaSDs4QwjBgDQC0kTHNYDgwflSePk71jS1JVBBRAG7ABM02eJG5niUAlADcQA/language/typescript

Somehow instead of doing an AST reformat that yields the same output each time, some part of the input is retained and informing the formatted output.

**Comment by dsherret** [comment]
> Somehow instead of doing an AST reformat that yields the same output each time, some part of the input is retained and informing the formatted output.

Yup, for the most part at the moment by default the input is retained and with objects they will try to stay compact and not expand to multiple lines like that since they are considered "inline-multilinable".
