### ISSUE TITLE
Feature Request: Trailing commas - ES5

### ISSUE THREAD

**Issue by kt3k** [dprint/dprint-plugin-typescript#288]
prettier has `es5` option for trailing commas settings, which roughly performs `OnlyMultiLine` where ES5 syntax allows it, and performs `Never` otherwise. Because `es5` is now default for the latest version of prettier (ref https://prettier.io/docs/en/options.html#trailing-commas ), I think we should support `es5` option as well (and maybe that should be the default?)

**Comment by kt3k** [comment]
Another motivation is that parameter trailing comma sometimes looks odd.

Here is the example of such case.
https://github.com/denoland/deno_std/pull/1028/files#r672383982

**Comment by kt3k** [comment]
I tried to implement the above halfway, but I wasn't sure it's good idea to add `ES5` variant to `TrailingCommas` enum because `es5` option is probably only meaningful for the global settings, and not appropriate for each settings such as `argument.trailingCommas`..

**Comment by dsherret** [comment]
Hey @kt3k, I thought about implementing this in the past. It makes sense that prettier implemented that years ago, but nowadays I don't think it's worth having an explicit option given that ES5 is on the way out the door.

That said, I think if someone really wanted this they could specify configuration like:

```
"typeParameters.trailingCommas": "never",
"arguments.trailingCommas": "never",
"parameters.trailingCommas": "never",
```

**Comment by kt3k** [comment]
Thanks for the input!

> but nowadays I don't think it's worth having an explicit option given that ES5 is on the way out the door.

Regarding this, I also searched the prettier repository and found [this](https://github.com/prettier/prettier/issues/11465). They look in agreement in changing the default to `all` in the future. Now I think the current default is just sensible! 👍
