### ISSUE TITLE
Debug panic when a file contains a tab in a comment block or js doc

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-typescript#298]
As title.

https://github.com/denoland/deno/issues/12211

**Comment by espindola** [comment]
Reduced testcase:

    fn main() {
        let path = std::path::PathBuf::from("foo");
        let cfg = dprint_plugin_typescript::configuration::ConfigurationBuilder::new().build();
        dprint_plugin_typescript::format_text(&path, "/*    */", &cfg).unwrap();
    }

make sure it is a tab in the comment.

**Comment by dsherret** [comment]
@espindola thanks again for reporting. I was previously wrong and this actually is a bug in the line width calculation because the tab could appear in a comment block (so a tab would count for 1 indent width instead of 2, 4, 8, etc. depending on the config) so this debug panic discovered an actual bug.
