### ISSUE TITLE
parens: IIFE needs to maintain wrapping parentheses to be valid

### ISSUE THREAD

**Issue by declanvong** [dprint/dprint-plugin-typescript#299]
**Describe the bug**

https://github.com/dprint/dprint-plugin-typescript/commit/cea7a7bb4002d8c515dda3f2f64a7ea1c11505b0 strips unnecessary parens, but they're required when wrapping an IIFE. With no parens, it's invalid JS: 

<img src="https://user-images.githubusercontent.com/13516619/134852221-f7c6b35c-cb0a-47fe-b6a8-b70e4016f2f7.png" width="50%"/>

Playground here: https://dprint.dev/playground/#code/BQMwrgdgxgLglgewgAhAhwCUyDeAoZQ5KJAZwQBsBTAOgoQHNgByACyovuQHcEAnCgBNmmANx4AvljFA/language/typescript

dprint-plugin-typescript version: 0.56.0, 0.56.1

**Input Code**

```ts
(function foo() {
    console.log('hello world');
}());
```

**Expected Output**

```ts
(function foo() {
    console.log('hello world');
}());
```

**Actual Output**

```ts
function foo() {
    console.log("hello world");
}();
```

**Comment by dsherret** [comment]
Thanks! I had no clue code could be written this way.
