### ISSUE TITLE
Comments in a generic arrow function disappear

### ISSUE THREAD

**Issue by declanvong** [dprint/dprint-plugin-typescript#303]
**Describe the bug**

As title; see playground link / examples below

dprint-plugin-typescript version: 0.56.2

**Input Code**

```tsx
<X>() => (
    <>
        {/* Comment 1 */}
        {/* Comment 2 */}
        {/* Comment 3 */}
    </>
);
```

**Expected Output**

```tsx
(<X>() => <>{/* Comment 1 */} {/* Comment 2 */} {/* Comment 3 */}</>);
```

**Actual Output**

```tsx
(<X>() => <>{} {} {}</>);
```

If you delete the `<X>` generic, it prints as expected:
```tsx
(() => <>{/* Comment 1 */} {/* Comment 2 */} {/* Comment 3 */}</>);
```

Playground link: [click here](https://dprint.dev/playground/#code/DwDQfAFAlABAvGGEBQM02GV6cG8D0AVDAMID2AthQKYB2ALjAIwyH4C+2OaBx5VdRgCZWHLt16lKNBjADMozjmD4sUANzJk+fDABK1CmQBu1GAANQYczACGtACYx6ACzMBjaYIDOMTzRgAI1t3AGsgA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kAA4AnRCMTbIUyAEc2ijIgDKGAJ7REwrbv3arCAOYOj5SEgDuADIIiADSlE7QIj6snIgAQtq8AMaI6lD+WNQAchbu8F6IwUgxUPxJqQAKihywGLCqThy8MkUhAKrwDhwcABK8BZ6lkLUFDvGKaLbVtfWNGjK8CBhL8MNIAB4YSjTaygBiKv4zdQ1rGpsYxY7GGEmwcAVKMovpkKrQtgCybND118NFJoDLwMIptCc5ucoJcAcYdHoDP1BgVhGIJIh4S4DPlCgD8Hc2JjfLxtHt-Ps2PBklCAHRxSqk6jYNJpJyLZarYb8BCk2wAUQ2CJ6Z1pj0QlQMguFtXmonEkl8ACsOBtaWYLNY7N4NAjXAARRRsfjeYwqtUyX7-EKM3RqYSE4msVoyfhSoW6EWqMU290ys5ohVOqB2YHBSxJaC0riaUmg8HheBoJqIORKFRrYzUNgyfWIZLQON0l1utyx5JDBarFYIYYccvWNhko1JzyVPbA7T1NkE7RE4yKfhK-MYaWe2XwaMNqxNvZUtBtjsGbvpR0DocjxkYCOT+spRvN+eLoHL2A9sBr3yhtoR8RT-czw+tgrtk9ds+rvvByA8+B8sdpBO96pI+c7Ph48R1P4sBcAAgkmsHaHUWCtPUyQAPKdvGhi9v2vjJIoLzMtctIiOCIENrBIgRlYhYcFkn54awBFqISNLgsBCR6OCEpMjQDHnuiirMaoHBsWC2jcLYwKcVREbZIg-ihIgtj+OCyb4EJ34sWJfY0u4Hh-hgTaILJ1EGApSkqWp2gafKGLGGgijIFgDxaqCqbMmZEYuW5ymqepDpflmQrghgeYFkWop7iBs4tguBTZC0iBoNKYWMd+ZHaAAkvANgea0NDeQY+wJtZgW4Zl4LoSI+WWIVGDFdopXaP5Nl2ZerBZXVnlFTFiBySVZUBbZQVMVA3UrPVXn9YNbipgoyiiWNmVUjSZwRYWSR0v18TcbotrMgJ6RacYIhrVCAFeruDZ7VlvF2iyXAnUGZ0XWcV1AbN5nNe9qhtRV9nCVAHiIBgsHJKkPQcbt+0PUdrIvQ5viwLVU29Y130RtlIgA6NlXGLAMiaGFm1Rd6-WgfFnhJa0aDZcT6UrWaqr8g4DWcXdPFWIgUTyCooweHwHi0bw9HM8qrMeoBZw7DWSDaJxVNHgUn0Bppr2+KhWCTJzcOHfxiOBsjrBcODkOATDt363xT2CZrrArB4oNoNwqaaIWlh6-d4YgtAEuO9JA3wPAFigtF1v3emcqnVeQewT0p4U5HPFq3KnUZK5Dg9RzWMGL5Dh4x1wUo4ZPG5FQzwNW7WxOGgOjLAAtLAZe6MMLeh7o+xuVXzI1xgdcNzQzet4gjciG5kAgAAviAQA/language/typescript)

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/2339

**Comment by declanvong** [comment]
This is actually significantly worse than what I originally raised -- updated test case, it's actually any comment in a generic function, not just in JSX in a generic function. I'll post on the swc ticket as well. 

https://dprint.dev/playground/#code/DwDQfAFAlABAvGGBvAUDdMD0mYAkCmANoQPYwDuJAToQCYoC+A3EA/language/typescript
