### ISSUE TITLE
Parentheses are removed around a destructuring assignment

### ISSUE THREAD

**Issue by declanvong** [dprint/dprint-plugin-typescript#306]
**Describe the bug**

When doing a destructuring assignment, parentheses around the statement is non-optional. However, they're stripped at the moment.

dprint-plugin-typescript version: 0.57

**Input Code**

```ts
({ a } = b())
```

**Expected Output**

```ts
({ a } = b())
```

**Actual Output**

```ts
{ a } = b()
```
(which is invalid JS).

![image](https://user-images.githubusercontent.com/13516619/136348806-2e4c01d1-9e25-4791-82c3-f9deccf03c1c.png)

Playground: [link](https://dprint.dev/playground/#code/BQbwBAhmC+YLxgEbAJQqA/language/typescript)

**Comment by declanvong** [comment]
WDYT of adding a config that would run a pass of `swc` (or an configurable external tool, since `swc` isn't fully mature yet) over the final output to re-validate that it's a valid AST?

**Comment by declanvong** [comment]
Raised a fix here: https://github.com/dprint/dprint-plugin-typescript/pull/308

**Comment by dsherret** [comment]
> WDYT of adding a config that would run a pass of swc (or an configurable external tool, since swc isn't fully mature yet) over the final output to re-validate that it's a valid AST? I can see issues like this popping up in the future, it would be nice to have a way to do an optional sanity check.

Sure! It would be easy to add.

Thanks again for the fix!
