### ISSUE TITLE
Ability to configure where operators are put & where line comments go

### ISSUE THREAD

**Issue by vlovich** [dprint/dprint-plugin-typescript#323]
Given a block like this:
```
return (
  n.length >= 3 && // 3-75 chars
  n.length < 75 &&
  /^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(n) && // lower alnum start and end, lower alnum + hyphens between
  !n.startsWith('some prefix') && // TODO we probably dont need to care about these last 2
  !n.endsWith('some suffix')
)
```

It gets formatted a bit strangely
```
return (
  n.length >= 3
  // 3-75 chars
  && n.length < 75
  && /^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(n)
  // lower alnum start and end, lower alnum + hyphens between
  && !n.startsWith('some prefix')
  // TODO we probably dont need to care about these last 2
  && !n.endsWith('some suffix')
)
```

Namely:
* I would expect to be able to request that math operators are anchored to the preceding line (I think this is the more common default that prettier uses?)
* Trailing line comment should either stay on the same line even if they go over the configured maximum OR they should be moved to the line preceding wherever the current line got moved to.

**Comment by dsherret** [comment]
Use `"operatorPosition": "sameLine"` config.

> Trailing line comment should either stay on the same line even if they go over the configured maximum OR they should be moved to the line preceding wherever the current line got moved to.

Yeah, it should. That could be improved.
