### ISSUE TITLE
Trailing comments following a namespace export declaration are stripped during formatting

### ISSUE THREAD

**Issue by lucacasonato** [dprint/dprint-plugin-typescript#324]
**Describe the bug**

Deno version: 1.16.2

https://dprint.dev/playground/#code/PQKhCgAIUgBAXAlvANgU0gETQBzQOwBMCBjAT0gFsBDfagczUoPihlkMQDMvESBXFPAoAjNPUT58aAE5s48BgGdIJFIgA0kYjhQB7Mm2DhwoGADFE6AFyQAdMB1K78FSGOngkACoALDNj4epBoJHpKZErwTJC+1CrUqnr4AG4siMmQ8MEyaAC0aAAeOHoy8JDUKCiQuZR60dq4BMT4JIhoKlwyepSeFY04zq6QvOgV5fD+NXr1kHpcWVO5JXY+vogqANZouCq19Rg6zaTtSn2l9LSIAF5ohFq0hJCS-UqS9GO61CRoduBFJTK0AqKl88HgOBG3UokAARGCIUprMBHAQ9HYUI9gFFCLAAAx2ACMhIALHY8cAEThgHVCC4lLCANz-YqlcoweKQHDUSZQnpwqlIlEtdGYojY+C4gnEskU7mTGl6OmuJkmMyQSw2ew06iSenQDwoyAAeUmshGVg6qloz0ogIm63w9E60IGQ2c4CAA/language/typescript

**Comment by dsherret** [comment]
Seems specific to export declarations. Maybe related to the feature that re-orders these (but doesn't occur with import decls for some reason).

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/pull/2813

**Comment by dsherret** [comment]
This was fixed a while ago.
