### ISSUE TITLE
Default value of `taggedTemplate.spaceBeforeLiteral` should probably be flipped

### ISSUE THREAD

**Issue by upsuper** [dprint/dprint-plugin-typescript#328]
Tagged template literals like
```
tag`text`
```
are currently formatted to
```
tag `text`
```
by default, which is controlled by `taggedTemplate.spaceBeforeLiteral`.

However, given that the tag is closely bounded to the template literal, and how it is documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) and other articles, I suggest that the default value should be flipped, i.e. there shouldn't be a space by default, matching the format people generally see on documentations.

**Comment by dsherret** [comment]
Yeah, it should be flipped. I think I just never use tagged templates to notice that the default was flipped from what I would expect too (and the deno config doesn't use a space here).
