### ISSUE TITLE
Option to disable new lines

### ISSUE THREAD

**Issue by DavidBernal** [dprint/dprint-plugin-typescript#33]
Hi, can I disable the new lines? 
For example, I have next code:
```
export function tryParseInt (element: unknown, radix: number = 10): number | null {
  try { return parseInt( element.toString(), radix ); }
  catch ( err ) { return null; }
}
```

It's convert to:
```
export function tryParseInt (
  element: unknown,
  radix: number = 10,
): number | null {
  try {
    return parseInt(element.toString(), radix);
  }
  catch (err) {
    return null;
  }
}
```

And I want to respect the line format. I can increment the lineWidth option but is not enough for try/catch:
```
export function tryParseInt (element: unknown, radix: number = 10): number | null {
  try {
    return parseInt(element.toString(), radix);
  }
  catch (err) {
    return null;
  }
}
```
Are there some way to fix that without set `// ignore` on every function?

**Comment by dsherret** [comment]
@DavidBernal how broad of a request is this? It adds a lot of complexity to get it to respect newlines in all scenarios so this would need to be done on a case-by-case basis.

Would the following format as-is?

```ts
try { const t = 5; return t; }
catch (err) { return null; }
```

What about:

```ts
try { return t; } catch (err) { return null; }
```

I'm not sure what the configuration would look like for this.

**Comment by DavidBernal** [comment]
Maybe add an option to disable the newline format could be nice. I don't know if has sense for you.

Anyway, is a promising formatter.
