### ISSUE TITLE
ASI may break code when preceded by an if statement containing a single expression statement

### ISSUE THREAD

**Issue by vedmalex** [dprint/dprint-plugin-typescript#335]
Version: 0.22.0

the code was generated by typescript is broken by {"semiColons": "asi"} 

[proof of the error](https://dprint.dev/playground/#code/AQ0iWBmwBQE4FMBGBXcAbAJsAvH4AbgPbjYAMAlMAN7CKobY7CQCG6AzggNzAC+AKDBgCrOHRQA7XCykBjAC7gi0mAjhwANMDkqFCAB4LtmFQirUhw66PHgZAWgCM3K9ZFjgkwwpmR5Siqw6lo6CgYWbu7W9gDUzC5R0WBQsACEIcAAZFnA9gA8wAD6CgAW4BwAdLqSkOAA5pUcCqz1CFXoCJL1ZZHJ-YSezTIl5VU1dY3Nre0A2uAAuq4DyTBk2nBSRURwRYYIcij6RU6Vm5Lbu-uH+hQwzdoh2ooGwGn4kijo6Nm5L2-4YikYBkYAAfjCrwAXDo9D5tN4jBRlitQIJUaAEJwEHloDB7AA+ZijCrVFSTJotNodLo9UrAAA+DOAIT6GOEpm8ag02hg-3ezE+31+kIBzCB5HBophNX0SORSQG6KVKP6iIU3NCsp8CuifG4QA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kXh1iQpkAI5tFGRAGUMAT2iJhm6AHdeFjgBFFbftd3lISewBkERABpSltoEW9WTkQAIQAnXgBjRHUoeyxqADljUwQAc2tApCiofkSUgAVFbQxYVVsOXhlEYsQAVXhrDg4ACV54fILSyG1B61jFNAtq2vr4WxleBAxlhb0kAA8MJRp45QAxFXtZ2DqGjS2MNpGMRNg4QaUZJbTIVWgLAFk2aDqbvSKAAOiESGEU8VO5wWl0Q2wBPiB8UQIlB-UGw3wYgkiD0SJRoLy41aQWE2MkPl48X29gObHgSWhADoYpUqdRsKlUos1qsECN+AgqRYAKKbfE9eZMx6ISqgsUS7QXUTiCmsABWHE2TMMxjMli8GnxqPibg8Xj0mu1Ml+-yCbORalsxtBIxaMn48vFyMlqml9q9ivmZNVuJ8lhBgRMiWgTK4QKpvHB8VC8DQjUQciUKnWPmobBkLkQSWgieZ7s98VMCaSmKgSxWaxGHBrZjY1PcaYKlX2IPidW5+DubDDrEU-HVxYwCp9Svgcdbpnb+3paG7vdBA7Sw9HUHHk8ZbIw0fnLeSbY7q-XwM3sEHYB3egjJOj4gX56Xl67gx7N-7d+3eIRz0QV4GFGdUjnd8Uk-Fdv3yWIznsWAuAAQTTVD4jOLAWjqJIAHk+yTCFhEfHwkkUF4OTaJkRAhGDW1QkRo1MUsOEyQDgPI1QOGHRkIWguIUQhWV2RoDj73JXdIAotQ+OTbgLBBQSmOjLJEHsYJEAsewIXTLFQz0WTeKAxk8nyMCMHbRAVOY0F1M07TdPifSVRxPQ0EUZAsAefUk0zDlbOjbzfK0nS9NIoDpLhIEIQwIsSzLKUzxg5dOzXQYsmaRA0AVOLOOkuj4gASXgcx-JaGggtBA4ITC5zXLI1givwkRypMSqMGq+JapTJyIqHKK9CK9qAqqlLEFUmq6v6lzIq45qIVGzrutMTMFGUHj5sK+lGXmBLSzBZLW1iYTkQdDkJLSKTht26EIN9U8TrO0THU5LhrsMnwRDu+YHqgiapp637VHqga3LVKB8kQDBUKSFIegEibTqK17Lq5T73J8WA2tWDrAsBuySpEMG5sGhaKBkWL+wOpK-Qm2D0oKLKWjQYqqfy7bLS1EVrBW5GXrWiJ5BUMZ8j4fJWK0BgHyGnwrX++Zdj5JB4kExmr0GRXlRunxcKwKZBJRkSLvEjGQyx1guFh+HIKR57UdN97JK+1hVnyaG0G4TMgVLEwjZeqNQXELnwyUyb4HgYwk2O89jeRbMdddqBn1Qnpb3ph2RO1mFZYpyAMl85aCcYomQusUnGrl1hYAskScioZ5Ou97ZbDQJEVgAWlrqPkRGHuRIOXym45FuMDbjuaG7uvkU7kRfMgEAAF8QCAA/language/typescript)

```javascript
        if (rebuild === void 0) { rebuild = false; }
        var run = function (err, context, done) {
            var i = -1;
            var next = function (err, ctx) {
                i += 1;
                if (!err && i < _this.config.stages.length) {
                    var st = _this.config.stages[i];
                    (0, run_or_execute_1.run_or_execute)(st, err, ctx !== null && ctx !== void 0 ? ctx : context, next);
                }
                else if (i >= _this.config.stages.length || err) {
                    done(err, (ctx !== null && ctx !== void 0 ? ctx : context));
                }
            };
            next(err, context);
        };
```

was broke to this

```javascript
if (rebuild === void 0) rebuild = false
var run = function(err, context, done) {
    var i = -1
    var next = function(err, ctx) {
        i += 1
        if (!err && i < _this.config.stages.length) {
            var st = _this.config.stages[i]
            (0, run_or_execute_1.run_or_execute)(
                st,
                err,
                ctx !== null && ctx !== void 0 ? ctx : context,
                next,
            )
        }
        else if (i >= _this.config.stages.length || err) {
            done(err, ctx !== null && ctx !== void 0 ? ctx : context)
        }
    }
    next(err, context)
}
```

**Comment by dsherret** [comment]
Issue is here as it turns it into a single statement:

```
var st = _this.config.stages[i]
            (0, run_or_execute_1.run_or_execute)(
                st,
                err,
                ctx !== null && ctx !== void 0 ? ctx : context,
                next,
            )
```

**Comment by vedmalex** [comment]
FYI: if I remove first line 
``` if (rebuild === void 0) rebuild = false ```
if works as expected

**Comment by dsherret** [comment]
> FYI: if I remove first line `if (rebuild === void 0) rebuild = false` if works as expected

Thanks for that information. It was key to this bug. I will release this fix later today.
