### ISSUE TITLE
Option to remove automatically insertable semicolons

### ISSUE THREAD

**Issue by Conaclos** [dprint/dprint-plugin-typescript#336]
Hi!

A lot of JavaScript and TypeScript projects don't use semicolons. Some famous style conventions such as [StandardJS](https://standardjs.com/) prohibit their use (except when needed).

I suggest to add an option `useSemicolon` that defaults to `true` and can be turned off in order to remove automatically insertable semicolons.

I think it is an option in the same vein as `useTabs` and `indentWidth`: for some people this improves code readability.

**Comment by dsherret** [comment]
I think this is implemented as the `"semiColons": "asi"` option?

https://dprint.dev/plugins/typescript/config/

**Comment by dsherret** [comment]
@Conaclos that's no problem!

By the way, in case you are using vscode, I think the json auto-complete for plugins in the dprint configuration is broken in the latest vscode. I have a release I'm going to push out later today that should fix it.

**Comment by Conaclos** [comment]
In fact I'm implicitly using `dprint` with `deno fmt`. Deno does not support most of the options exposed by dprint, including semicolons... I opened an issue for that. However, I'm a bit skeptical because they seem reluctant to add this kind of options...
