### ISSUE TITLE
dprint-ignore removes export from const enum

### ISSUE THREAD

**Issue by rope-hmg** [dprint/dprint-plugin-typescript#343]
**Describe the bug**

When adding a `// dprint-ignore` comment to a `const enum` dprint will remove the `export` keyword. Without the comment everything works as expected.

dprint-plugin-typescript version: 0.62.0

Playground link using 0.64.0
https://dprint.dev/playground/#code/PTAEBMAcCcEsDsAuBaWBzeB7aBTAUDgB6TaKgDGm8AzmTvAK4C2oAgqAN4C+QA/language/typescript

**Input Code**

```ts
// dprint-ignore
export const enum A {}
```

**Expected Output**

```ts
export const enum A {}
```

**Actual Output**

```ts
const enum A {}
```

**Comment by dsherret** [comment]
Definitely sounds like an swc bug. I will look into it. Thanks for reporting!

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/pull/3701

**Comment by dsherret** [comment]
This has been fixed for a while.
