### ISSUE TITLE
arrowFunction.useParentheses = preferNone removes parens that are required with optional param

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint-plugin-typescript#348]
**Describe the bug**

dprint-plugin-typescript version: 0.64.2

With `"arrowFunction.useParentheses": "preferNone"` set, parens are removed from the following code, even though doing so makes the code invalid.

[Playground Link](https://dprint.dev/playground/#code/GYVwdgxgLglg9mABMOcAUBKRBvAsAKESMQCcBTKEEpPQ4+gcwoDEBDAGwGcyAVATwAOZAFyI0wcpwAWAfiwBeAHzJJUxDOQdu-IYlHkGIdqxJsuvQWQA0BegF8CdoA/config/N4KABGBECGBOsHsDuAxArgOwMYBcCWCGAdGgM4CmACnORjgBbkWmQBcUADrOQGbmwA5QuUggAviCA/language/typescript)

**Input Code**

```ts
function foo() {
    return {
        getFalseType: (fresh?) => fresh ? falseType : regularFalseType,
    }
}
```

**Expected Output**

```ts
function foo() {
    return {
        getFalseType: (fresh?) => fresh ? falseType : regularFalseType,
    };
}
```

**Actual Output**

```ts
function foo() {
    return {
        getFalseType: fresh? => fresh ? falseType : regularFalseType,
    };
}
```

**Comment by jakebailey** [comment]
Thank you!

**Comment by dsherret** [comment]
@jakebailey and thanks for reporting! Will be in 0.65.0 (just doing a release now)
