### ISSUE TITLE
When increment/decrement operator is mixed with `as`, the parentheses should not be removed

### ISSUE THREAD

**Issue by justjavac** [dprint/dprint-plugin-typescript#351]
**Describe the bug**

https://dprint.dev/playground/#code/BQQwBCDOYHYK4FsBGBTATgSgNRaA/language/typescript

deno 1.20.1+c98c976 (canary, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2

**Input Code**

```ts
(a as number)++
```

**Expected Output**

```ts
(a as number)++;
```

**Actual Output**

```ts
a as number++;
```

**Comment by dsherret** [comment]
@justjavac thanks! Will be in 0.56.1 and doing a release now (missed this issue so it missed getting in 0.56.0)
