### ISSUE TITLE
Keep trailing comma on arrow function type parameter in mts and cts files

### ISSUE THREAD

**Issue by sounisi5011** [dprint/dprint-plugin-typescript#378]
Starting with TypeScript 4.5, the following code now throws an error.

```ts
export const x = <T>(value: T): T => value;
```

```text
error TS7060: This syntax is reserved in files with the .mts or .cts extension. Add a trailing comma or explicit constraint.
```

To fix this code, it should be rewritten as follows either:

```ts
export const x = <T extends unknown>(value: T): T => value;
```

```ts
export const x = <T,>(value: T): T => value;
```

dprint formats the second example code to the original unfixed code.

Reference:

+ https://github.com/microsoft/TypeScript/issues/15713
+ https://github.com/prettier/prettier/issues/6114
+ https://github.com/prettier/prettier/issues/6302
+ https://github.com/prettier/prettier-vscode/issues/955

**Comment by dsherret** [comment]
There are a few instances where this occurs that dprint-plugin-typescript already handles. In this case, here is the relevant code in TypeScript and it's specific to mts and cts files:

```ts
        function checkGrammarArrowFunction(node: Node, file: SourceFile): boolean {
            if (!isArrowFunction(node)) {
                return false;
            }

            if (node.typeParameters && !(length(node.typeParameters) > 1 || node.typeParameters.hasTrailingComma || node.typeParameters[0].constraint)) {
                if (file && fileExtensionIsOneOf(file.fileName, [Extension.Mts, Extension.Cts])) {
                    grammarErrorOnNode(node.typeParameters[0], Diagnostics.This_syntax_is_reserved_in_files_with_the_mts_or_cts_extension_Add_a_trailing_comma_or_explicit_constraint);
                }
            }
        }
```

Will open a fix soon.
