### ISSUE TITLE
published rendered documentation of all configuration options

### ISSUE THREAD

**Issue by adrian-gierakowski** [dprint/dprint-plugin-typescript#385]
couldn't find much on https://dprint.dev/config/ and had to search to codebase to eventually find [this file](https://github.com/dprint/dprint-plugin-typescript/blob/f9eb1986168489ce1baf54404592032c2b54fcfb/deployment/schema.json)

**Comment by adrian-gierakowski** [comment]
Thanks! Not sure how I missed it :)

**Comment by dsherret** [comment]
Good to know that people might be looking for the plugin config there though. I updated https://dprint.dev/config/ to have a section on where to view plugin/language specific configuration.
