### ISSUE TITLE
No error when unary operator + expression + dot

### ISSUE THREAD

**Issue by lazex** [dprint/dprint-plugin-typescript#391]
**Describe the bug**

dprint-plugin-typescript version: 0.69.5

**Input Code**

```js
+value.
```

**Expected Output**

Error.

**Actual Output**

```js
+;
```

https://dprint.dev/playground/#code/NQNwhgNgrgpgdAWAFBA/language/typescript

**Comment by dsherret** [comment]
@lazex thanks for reporting these! I will do a release in the next few days.

**Comment by lazex** [comment]
Thanks for the correction. However, the error does not occur in this case.

```js
+value.;
```

https://dprint.dev/playground/#code/NQNwhgNgrgpgdAbgLACgg/language/typescript

**Comment by dsherret** [comment]
@lazex appreciate you pointing these out! I merged https://github.com/dprint/dprint-plugin-typescript/commit/e75bc3b3e2c2abe2f166b3a7d81d9af702913d1f and this will be fixed in 0.71.1 (CI is just running doing the release now)
