### ISSUE TITLE
Add ability to disable import ordering

### ISSUE THREAD

**Issue by stephenh** [dprint/dprint-plugin-typescript#399]
In a large TypeScript codebase, we use this pattern for avoiding circular import errors between files:

https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de

I.e. we create a "barrel export" file (that all it does is export symbols from other files) with a very specific order of:

```
export { Foo } from "./foo";
export { Bar } from "./bar";
```

And we don't want these re-ordered.

Using `// dprint-ignore-file` turns off formatting for the entire file, but then (b/c this file is generated from some code generation templates that purposefully don't care about formatting) the whole file ends up ugly/unformatted.

So I'd like to disable _only_ the import reordering, but still get the rest of the dprint formatting.

Could this be done via either a config parameter or an in-file hint? (Granted, in-file hints for specific behavior is not great, but I think the general important of import ordering to runtime behavior/correctness makes this a valid exception). 

We had been using `prettier-plugin-organize-imports` and it has a `// organize-imports-ignore` that served this purpose. Thanks!

**Comment by stephenh** [comment]
Huh, I found that `dprint-node` happens to not organize imports, and all it does is set `deno: true`; I have no idea what else that flag does, but for now I'm borrowing it to turn off organize-imports just for our one barrel file. :-) 

So I'm unblocked, but would still be neat to have a dedicated flag / in-file token I think. Thanks!

**Comment by dsherret** [comment]
See https://github.com/dprint/dprint-plugin-typescript/issues/369#issuecomment-1131939797

**Comment by stephenh** [comment]
Ah! I was going to say, I swear I searched the docs. :-) Np though! Thanks!

**Comment by stephenh** [comment]
I already closed the issue, but then thought: is there a way to set dprint settings from within a file?

Like making something up:

```
// dprint-module-sortImportDeclarations-maintain
```

I don't personally need that right now, b/c I'm continually re-generating this barrel file anyway, and so can set the "sortImportDeclarations: maintain" flag only for this one file.

But in theory if we wanted to start using dprint across our whole codebase, and run like `dprint ...all our files..`, then we would want `sortImportDeclarations` on for ~99% of the files (I do like the feature!), but disabled just for these special/esoteric barrel imports.
