### ISSUE TITLE
Space removed after method call on number literal

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint-plugin-typescript#421]
**Describe the bug**

dprint-plugin-typescript version: 0.73.1

**Input Code**

```ts
1+ 2 .toString() +3
```

**Expected Output**

```ts
1 + 2 .toString() + 3
```

or

```ts
1 + 2..toString() + 3
```

or

```ts
1 + (2).toString() + 3
```

**Actual Output**

```ts
1 + 2.toString() + 3;
```

Prettier adds parens; I think that's probably the best thing to do. See also: https://github.com/microsoft/TypeScript/issues/50686

**Comment by dsherret** [comment]
TIL

**Comment by jakebailey** [comment]
Fixing this right now for TS's own formatter, so... 😅 

The double dot only works because `2` and `2.` are the same in JavaScript. Not so much in Python, where this syntax is also valid. (I fixed the same bug before there too...)
