### ISSUE TITLE
nextControlFlowPosition doesn't apply to do/while

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint-plugin-typescript#429]
**Describe the bug**

dprint-plugin-typescript version: 0.74.0

With `nextControlFlowPosition=nextLine`, `while` is left on the same line as the brace.

**Input Code**

```ts
do {
    console.log("hello")
} while (1 === 1);
```

**Expected Output**

```ts
do {
    console.log("hello")
}
while (1 === 1);
```

**Actual Output**

```ts
do {
    console.log("hello");
} while (1 === 1);
```

[dprint playground](https://dprint.dev/playground/#code/JYMwBAFAjGC89igSjAbwLACgw7AYwHsA7AZwIBsBTAOnIIHMIAiAFwCcBXSppLAXzCVyJSmiy58xMlVoNmIAIbDuvTHyxYAJgTHZchUhRp1GTABZC6PfmADuZ4FUgx4sREgDcQA/config/N4WAUABFEEQJYDsAmBTBAXA6nJ6AWMAXBACwA040sANoitrgcQIwAM7Fk0MCKA7gBk6AaURIisAIYBXdAHsYnKjGkBnFABVJAI1USAZpOrql3dQFs4AYTnU5CPcRhG+kgJ57TUGAEdpc9BQAZXQ3ahQJGAAHACcUfRQYgBE5aW1wxUpuNRQAIRjJAGMUR1g+PDQAOQCgxABzcKFeTK5vbQLigAU5VTh0OHtI1UlzFCaUAFUEcNVVAAlJBDr6luVepfDcuSQ3bt7+wadh0fHV7l4AD3QbDBjbADE7Pj2+gYRI80lEdC-3r1h0AU4LQljZzJ9SjB7NQ3ABZaTUfqnf7OGJ3Pj3aQIQoHBAAOhynUkcQwFXUkNi8US1WaKMK9iQr3sRgAohdKbM3niQShOok2RzeocIIZjCgUfosTi3gK4pz7HjVFEiigAIL6QIxTHY3HCFBuPhyGLiYiA6TirLeSkJGILJYrYiikyW2ByKKJSTyGIvXEfX4-RBnbzmbYIlCKo3oACS5iikaSKEK1GJnrekM+31+QdgIaQYYjMXQAvjieTBVx6f9WZRKHZJaTKdxBfQlRGKCQxcLlczgZRcFj9bLqYVqkjrdGSBjca7fp7fxdMHpDjNOKNGjc7sVyuK6s1lX4eoNRpNEDNFtasCXqhX6FqdQQnukcS3Kt31IP+sNxokZ-AAF9wCAA/language/typescript)

Additionally, `maintain` doesn't work if the keyword is already on the next line:

**Input Code**

```ts
do {
    console.log("hello")
}
while (1 === 1);
```

**Expected Output**

```ts
do {
    console.log("hello")
}
while (1 === 1);
```

**Actual Output**

```ts
do {
    console.log("hello");
} while (1 === 1);
```

**Comment by dsherret** [comment]
This was just not implemented 😅. Should be released now in 0.75.0
