### ISSUE TITLE
WAMS supported js code

### ISSUE THREAD

**Issue by Kuranes** [dprint/dprint-plugin-typescript#430]
[it has defines, it has specific keywords and constructs](https://github.com/emscripten-core/emscripten/blob/77da62969eb0b5efe4ce4a0c9ce67c45b9e32638/src/library_browser.js)

currently formatters breaks everything on it

**Comment by dsherret** [comment]
This is non standard javascript and prettier doesn't support it either. I don't think it would ever be supported because it's not standard and it would require support in swc.

```ts
#if MAIN_MODULE
```
