### ISSUE TITLE
Option to ignore JSX attributes (don't force attributes on new lines)

### ISSUE THREAD

**Issue by JesseVelden** [dprint/dprint-plugin-typescript#433]
I know I'm maybe weird, but I want sometimes to have JSX elements with multiple attributes per line. So basically I would like dprint to not touch JSX attributes at all. (The `jsxAttributes.preferSingleLine` option isn't that useful for this either.) 

Maybe only put the last attribute on a new line, if it exceeds the line width. So that something like this would still be valid:
```jsx
<Input type='text' className={textClass} style={{ width, maxWidth }} 
    defaultValue={defaultValue} placeholder={placeholder} {...props} />
```

**Comment by dsherret** [comment]
Set `"jsxAttributes.preferHanging": true` in the config for the typescript plugin.

https://dprint.dev/playground/#code/LAKAxg9gdgzgLgAjgU3ggvAgPAEwJYBuAfKFgJJQAOAronAJ6XLoDkKAHnCwmADYCGMGADl+AW2YBvDnADCAoQF8E8erymSEAdzw44ACwA0CMf3YB1XQYSLloBA4Q5kAM37VecAGr9e1Kc5uHt6+-sqUAmDI+hC8zgBO6JIR-FExccjxypIAdHmU8RCUMMoA9CQgWKX4xEA/config/N4WAUABFEEQFYGcAeBBALmgTgSwEYFc0BTBAOgAdMiAzIzACQEMA7Ac2zZgC4It8jwAXyA/language/typescript

**Comment by dsherret** [comment]
@JesseVelden could you open a new issue following the issue template for a bug? It will ask you for expected output which will help communicate what's wrong. Thanks.

**Comment by JesseVelden** [comment]
Alright! I created a new bug report here: https://github.com/dprint/dprint-plugin-typescript/issues/436
