### ISSUE TITLE
Preserve empty lines

### ISSUE THREAD

**Issue by user72356** [dprint/dprint-plugin-typescript#439]
Consider this:

```ts
export default withApiAuth(

    async function handler(req, res)
    {



    }
);
```

There should be an option to preserve the empty lines in general. In the example above, there is an empty line before the inline function and also within the function itself. This is useful sometimes to increase code clarity.

**Comment by dsherret** [comment]
I think it would be too much of a maintenance burden to implement, so I'm going to decline this one. Sorry.
