### ISSUE TITLE
Extra space in JSX self-closing components

### ISSUE THREAD

**Issue by MariaSolOs** [dprint/dprint-plugin-typescript#445]
**Describe the bug**

dprint-plugin-typescript version: 0.76.0

It seems like the new `jsx.bracketPosition` setting is adding an extra space to self-closing elements.

**Input Code**
```json
// dprint file
{
    "indentWidth": 4,
    "typescript": {
        "quoteStyle": "alwaysSingle",
        "jsx.quoteStyle": "preferDouble",
        "trailingCommas": "never",
        "jsx.bracketPosition": "sameLine"
    },
    "includes": [
        "**/*.{ts,tsx,js,jsx,cjs,mjs}"
    ],
    "excludes": [
        "**/node_modules",
        "**/*-lock.json"
    ],
    "plugins": [
        "https://plugins.dprint.dev/typescript-0.76.0.wasm"
    ]
}
```

```tsx
<MyComponent someProp={value} />
```

**Expected Output**

```tsx
<MyComponent someProp={value} />
```

**Actual Output**

```tsx
<MyComponent someProp={value}  />
```

**Comment by MariaSolOs** [comment]
As a follow-up, would it be too much to ask to have separate settings for regular and self-closing JSX elements? I feel awful asking this after the initial setting was so quickly implemented 🥲 

For example, I would like this:
```tsx
<MyComponent 
  name="name"
  value="value"> // bracket in same line
</MyComponent>

<MyComponent
  name="name"
  value="value"
/> // bracket in separate line
```

**Comment by dsherret** [comment]
Oops. Will take a look soon.

Yeah, I could split those up and have this as a high level property.

**Comment by MariaSolOs** [comment]
@dsherret Thanks a lot! Please let me know if you need anything else from me (regarding repro steps or anything really).

**Comment by dsherret** [comment]
Will be released in 0.77 once the ci finishes running.

**Comment by MariaSolOs** [comment]
You're amazing, thanks @dsherret!

**Comment by MariaSolOs** [comment]
And I think you meant `"jsxOpeningElement.bracketPosition"` right? ;)

**Comment by dsherret** [comment]
Yes, sorry. I updated the PR title. At least it was correct in the code 😅
