### ISSUE TITLE
`@` decorator usage in JavaScript files causes errors

### ISSUE THREAD

**Issue by scottbessler** [dprint/dprint-plugin-typescript#484]
**Describe the bug**

dprint-plugin-typescript version: 0.81.1

Decorators don't work in JS & JSX files, even though typescript (and prettier) support it.

[Playground link](https://dprint.dev/playground/#code/MYGwhgzhAEBiD29oG8CwAoa0ACYCuALvAEYCWAdgCYZbFgBOAFAJQo1bT0CmBe950AIwBudgF8MYoA/config/N4KABBYEQDYJYDsCmB1OATALgCygLjAEYAmABgBpxIpF0kFM0tcDjLJoArAZwA8A6AI4BXAPaYkAZUwBPGEnzQADgCckAMyQqAIqOEAjeVHbVRSrQENMolQAVR3OJjiiEiqAFsLiTN7cmIKBFxKVkjAihVDS1JRABzIxAAXxAgA/language/typescript) (although you'll have to change the dropdown to js/x)

**Input Code**

```jsx
class Foo {
  @autobind
  bar() {
    return 1;
  }
}
```

**Expected Output**

```ts
class Foo {
  @autobind
  bar() {
    return 1;
  }
}
```

**Actual Output**

```ts
Unexpected token `@`. Expected identifier, string literal, numeric literal or [ for the computed key at file.jsx:2:3

    @autobind
    ~
```

**Comment by scottbessler** [comment]
dang that is some response time! thank you so much!!

**Comment by scottbessler** [comment]
@dsherret not to be that guy, but when would you expect a release to be cut with this enhancement? and/or is there a way to reference a specific unreleased commit as a dprint plugin? Thanks :)

**Comment by dsherret** [comment]
Sorry, I was going to do get a few more things in, then do a release, but then I got busy. I just kicked off a release now and it will be available once the CI finishes running (in maybe 15-25 mins)

**Comment by scottbessler** [comment]
@dsherret again, thanks for the lightning fast responses!
