### ISSUE TITLE
Syntax error for missing close paren are formatted incorrectly

### ISSUE THREAD

**Issue by lazex** [dprint/dprint-plugin-typescript#498]
**Describe the bug**

dprint-plugin-typescript version: 0.83.0

**Input Code**

```ts
const foo = <T extends {}>() => {
    if (bar() {
        console.log(1);
    }
};
```

The closing parenthesis for if is missing.

**Expected Output**

Syntax error.

**Actual Output**

```ts
const foo = <T extends {}>() => {
    if (bar()) {
        if (bar();
    }
    {
        console.log(1);
    }
};
```

**Comment by dsherret** [comment]
I opened https://github.com/swc-project/swc/issues/7104
