### ISSUE TITLE
What is this plugin for and how to use it?

### ISSUE THREAD

**Issue by cdpark0530** [dprint/dprint-plugin-typescript#504]
This is just a pure question.

What is this plugin for and how to use it briefly?
(I can't find any clue on the internet, and I can't guess anything from the readme of this plugin)

I'm asking about this when I'm trying to find a way to run `dprint` as formatter in `eslint` like you can do it with `prettier` in `eslint`. I found `eslint-plugin-dprint` which seems to be 3rd party plugin, but that one does not even follow workspace's `dprint.json`. I'm hoping `dprint-plugin-typescript` is what I'm looking for.

**Comment by so1ve** [comment]
This is a dprint plugin which allows dprint to parse and format js/ts code.

I don't understand your meaning - what are you going to do?

**Comment by so1ve** [comment]
I have made an eslint plugin to make dprint work with it like what eslint-plugin-prettier does. Here it is: https://github.com/so1ve/eslint-plugin-dprint-integration. Docs are WIP but soon :)

**Comment by cdpark0530** [comment]
@so1ve So this `dprint-plugin-typescript` is a plugin for `dprint` core, but this is not for `eslint`? And what I was looking for is rather `eslint-plugin-dprint-integration` I guess.

**Comment by so1ve** [comment]
> @so1ve So this `dprint-plugin-typescript` is a plugin for `dprint` core, but this is not for `eslint`? And what I was looking for is rather `eslint-plugin-dprint-integration` I guess.

Yes, it is a plugin for dprint core.
