### ISSUE TITLE
const type parameters get removed

### ISSUE THREAD

**Issue by ivanhofer** [dprint/dprint-plugin-typescript#508]
**Describe the bug**

`dprint` removes const type parameters [intorduced in version 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters)

dprint-plugin-typescript version: 0.84.0

[Playground link](https://dprint.dev/playground/#code/KYDwDg9gTgLgBAYwgOwM7wGbLgXjgHiTXgBEBDGMuUGYZAE1TgCVgz6UAbATwEEooZbvgCuyANbIIAd2QA+OQAowQzhHYAuOOUoBKXHLgrua9kA/language/typescript)

**Input Code**

```ts
export const fn = <const Data extends ReadonlyArray<unknown>>(payload: Data) => payload
```

**Expected Output**

```ts
export const fn = <const Data extends ReadonlyArray<unknown>>(payload: Data) =>
  payload;
```

**Actual Output**

```ts
export const fn = <Data extends ReadonlyArray<unknown>>(payload: Data) =>
  payload;
```

**Comment by dsherret** [comment]
I opened https://github.com/swc-project/swc/pull/7242
