### ISSUE TITLE
Deletes everything inside the file when theres an error

### ISSUE THREAD

**Issue by kasdeya** [dprint/dprint-plugin-typescript#563]
**Describe the bug**

Formatting when theres errors like these will clear the file out leaving it blank.

dprint-plugin-typescript version: 0.87.1

**Input Code**

```tsx
Accidental typo "consta" 
function App () {
consta test = "hello"
return(<div>hello</div>)
}
```

**Expected Output**
Expect nothing to happen or format what it can.
```tsx
function App () {
consta test = "hello"
return(<div>hello</div>)
}
```

**Actual Output**
Everything gets cleared.
```tsx

```

**Comment by dsherret** [comment]
Can you post your reproduction steps? I get the following with the latest dprint and dprint-plugin-typescript:

```
Error formatting C:\Users\david\dev\scratch\main.tsx. Message: Expected ';', '}' or <eof> at C:/Users/david/dev/scratch/main.tsx:2:10

    consta test = "hello"
           ~~~~
Had 1 error(s) formatting.
```

**Comment by kasdeya** [comment]
never mind, user error. sorry!.

**Comment by dsherret** [comment]
No problem! It has spurred me to open https://github.com/dprint/dprint/issues/750 for the future
