### ISSUE TITLE
Formatting bug when using multi-line strings

### ISSUE THREAD

**Issue by lironhl** [dprint/dprint-plugin-typescript#565]
Hi!
seems like I ran into a problem when using multi-line strings

**Describe the bug**

dprint-plugin-typescript version: 0.88

**Input Code**

```ts
describe(
    "Im testing dprint I should be hanging \
    I should be hanging",
    async () => {
        // test
    }
)
```

**Expected Output**

```ts
describe(
    "Im testing dprint I should be hanging \
    I should be hanging",
    async () => {
        // test
    },
);

```

**Actual Output**

```ts
describe(
"Im testing dprint I should be hanging \
    I should be hanging",
    async () => {
        // test
    },
);

```

Seems like the code inside `dprint/core` doesn't take into account all the possible ways of creating multi-line strings

```rust
fn gen_from_raw_string_lines(text: &str, gen_line: impl Fn(&str) -> PrintItems) -> PrintItems {
  let add_ignore_indent = text.contains('\n');
  let mut items = PrintItems::new();
  if add_ignore_indent {
    items.push_signal(Signal::StartIgnoringIndent);
  }
  items.extend(gen_string_lines(text, gen_line));
  if add_ignore_indent {
    items.push_signal(Signal::FinishIgnoringIndent);
  }
  items
}
```

I've tried to tackle this myself but I've no idea which other crates besides `dprint-plugin-typescript` are using `dprint/core` and what would be the consequences of changing such a basic function :\

**Comment by dsherret** [comment]
@lironhl thanks for reporting! I took a look and wasn't an issue in dprint-core. There trick to make it work is by making the inner part of the string ignore indentation, but not the outside.

I kicked off a release so this should be available in about 5 minutes.

**Comment by lironhl** [comment]
> @lironhl thanks for reporting! I took a look and wasn't an issue in dprint-core. There trick to make it work is by making the inner part of the string ignore indentation, but not the outside.
> 
> I kicked off a release so this should be available in about 5 minutes.

Oops...
Thanks!
