### ISSUE TITLE
Allow different quoteStyle inside of JSX

### ISSUE THREAD

**Issue by sstackus** [dprint/dprint-plugin-typescript#592]
Need a way to specify single quote style in TS but double quotes for JSX element props/attributes, e.g.:

```tsx
const a  = 'single';
(<Component prop="double" />)
```

---

*Rant:* Might be a headache for you guys and trigger an out of scope/don't care response, but this is a very common scenario and would help dprint adoption given the number of TS devs being also React devs.

**Comment by dsherret** [comment]
> Rant: Might be a headache for you guys and trigger an out of scope/don't care response, but this is a very common scenario and would help dprint adoption given the number of TS devs being also React devs.

Why rant when it's already implemented?

```
{
  "quoteStyle": "preferSingle",
  "jsx.quoteStyle": "preferDouble"
}
```

https://dprint.dev/playground/#code/MYewdgziA2CmB00QHMAUByAFgS3QSgG4AoUSAFwAJKBeCgHgFE4BbWMSgBwCcQPqAiAG4BDaAFdY-CgHoAfEA/config/N4KABGBECOCuD2AXApgZUQTwDbMgLigAcAnZAM2WNQEsA7Acx0gBpwoArAZwA8A6OJGkxMCkEuUoAReLABGTEAF8QQA/plugin/typescript
