### ISSUE TITLE
Format breaks file with merge conflict

### ISSUE THREAD

**Issue by otakustay** [dprint/dprint-plugin-typescript#599]
**Describe the bug**

dprint-plugin-typescript version: 0.88.8

**Input Code**

```ts
export * from './schema.js';
export {readPluginDescription} from './reader.js';
<<<<<<< HEAD
export {ACTION_CHAT_QUERY, ChatQueryParsed, ChatQueryPayload} from './bridge/chat.js';
=======
>>>>>>> 2a5bf36 (ee-fe-796 修改对话回传消息的格式)
export {VisibilitySelectorMatcher, LanguageDetector} from './visibilitySelector/index.js';

```

**Expected Output**

Leave it unmodified

**Actual Output**

```ts
// HEAD
export { ACTION_CHAT_QUERY, ChatQueryParsed, ChatQueryPayload } from './bridge/chat.js';
export { readPluginDescription } from './reader.js';
export * from './schema.js';
//
// 2a5bf36 (ee-fe-796 修改对话回传消息的格式)
export { LanguageDetector, VisibilitySelectorMatcher } from './visibilitySelector/index.js';

```

Merge conflict are removed and changed to comment, this is very dangerous, I may miss some conflict and get a wrong code

**Comment by magic-akari** [comment]
The parser of SWC generates a recoverable error (TS1185).

- related: swc-project/swc#5775

**Comment by dsherret** [comment]
Yeah probably just needs to be added here: https://github.com/dprint/dprint-plugin-typescript/blob/52d2c91ec40be70b6d20f26627df7ee89a42ce17/src/swc.rs#L54

It's a simple fix if someone wants to submit a PR. Otherwise I'll try to fix it soon
