### ISSUE TITLE
Ability to increase line width of a node

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-typescript#6]
It would be cool if in certain cases you could just say "I don't care... format this part, but let it go long".

Something like:

```ts
// dprint-line-width: 180
```

Edit: I think this would just need to be something like `Signal::StartLineWidth(180)` then `Signal::EndLineWidth` (stored in a stack with the first line width as the first item... the stack should never be empty)

**Comment by declanvong** [comment]
With the new enhancement request to control JSDoc wrapping in some cases, what do you think of a more general solution to this that would resolve both?

1. Add a new config option similar to `ignore_node_comment_text` such as `override_node_comment_text`, defaulting to `dprint-override`
2. It takes a string after the comment text that's similar to how they're set in unit tests, e.g. comma separated list of config options

e.g. it might look something like
```
// dprint-override lineWidth: 60
this.is.a.line.that.can.go.over60.chars.if.needed;
```
or 
```
// dprint-override jsx.quoteStyle: preferDouble, lineWidth: 20, arguments.preferHanging: always
thisLineWouldhaveDoubleQuotes
  .haveALineWidthOf20(
     and, prefer, hanging
  );
```

That said, if it's for the next (whole) node, it may get a little confusing... e.g. if it's a function declaration node, that would therefore include the body, right? So then you'd maybe need to do another override back to the defaults inside the body, if you really only care about ignoring it for the function signature. 
And if it's next line only, I can see that being quite brittle if lines are changed or made multiline after reformatting 🤔

**Comment by dsherret** [comment]
Neat idea for both of these, but it would add way too much complexity. I would suggest people just use `// dprint-ignore` comments.

**Comment by gustavopch** [comment]
Suppose line width is 18.

This:
```ts
console.log('bla')
console.log('lala')
console.log('foo')
```

Gets formatted to this:
```ts
console.log('bla')
console.log(
  'lala'
)
console.log('foo')
```

Not only uglier, but objectively harder to read.

Ideally, I'd like the formatter to have some sense of aesthetics, but that's probably not possible (well, maybe when we have an LLM-based formatter), so second best way would be:
```ts
console.log('bla')
console.log('lala') // dprint-line-width: 180
console.log('foo')
```

- Comment at the end of the line, so it doesn't draw much attention.
- Other formatting would still work, so if I typed `console.log(  'lala' )` the extra spaces would still be removed.
