### ISSUE TITLE
Request: Smarter import/export declaration name order

### ISSUE THREAD

**Issue by KSXGitHub** [dprint/dprint-plugin-typescript#60]
I desire this order:

```javascript
import { ABC_DEF, GHI_JKL, AbcDef, GhiJkl, abcDef, ghiJkl } from 'somewhere'
export { ABC_DEF, GHI_JKL, AbcDef, GhiJkl, abcDef, ghiJkl, default }
```

**Rule explanation:**

* sort by keyword first (`default`)
* within non-`default` names, sort by case (UPPER_SNAKE_CASE, CapitalCase, camelCase, snake_case, miXed_CASE)
* within the same case group, sort by alphabetical order

**Comment by dsherret** [comment]
I’m thinking this might be too specific—someone may want a different order similar to this. What do you think this sort order would be called? Right now there is “caseSensitive”, “caseInsensitive”, and “maintain”

**Comment by KSXGitHub** [comment]
You may consider my "too specific" rule explanation as a subset of a more generic use case.

A generic data type would be something like this:

```rust
pub enum SortOrder {
    Maintained,
    CaseSensitive,
    CaseInsensitive,
    Groups(Vec<SortGroup>), // new!
}

pub enum SortGroup {
    DefaultExport,
    UpperSnakeCase(NameOrder),
    CapitalCase(NameOrder),
    CamelCase(NameOrder),
    SnakeCase(NameOrder),
    EverythingElse,
}

pub enum NameOrder {
    Maintained,
    Ascending,
    Descending,
}
```

Then my desired configuration would be:

```rust
use SortGroup::*;
use NameOrder::*;
let order = SortOrder::Groups(vec![
    UpperSnakeCase(Ascending),
    CapitalCase(Ascending),
    CamelCase(Ascending),
    EverythingElse, // both snake_case and mixed case is second last, only before default export
    DefaultExport,
]);
configuration_builder
    .import_declaration_sort_named_imports(&order)
    .export_declaration_sort_named_exports(&order);
```

**Comment by dsherret** [comment]
I think this is too much complexity and believe there may be some disagreement about what the groups are—some people might want to split up some of the groups into even more sub groups. The line has to be drawn somewhere so I'm going to draw it at the current configuration.

If a custom sort order like this is desired, then I would recommend changing the setting to "Maintain" then having another tool do another pass on the file to do the sorting.

**Comment by KSXGitHub** [comment]
> If a custom sort order like this is desired, then I would recommend changing the setting to "Maintain" then having another tool do another pass on the file to do the sorting.

Doing so would require parsing a file twice, which is sub-optimal. Can you expose a `format_text`-like function that takes an AST? Alternatively, you may provide `SortOrder::Custom(Box<dyn Fn(&str, &str) -> Ordering>)` variant (which would be serialized to `"maintain"` in the config file).

---

Both approaches I mentioned above still have disadvantages:
* They are not easy to distribute: For my tool, I would have to create another CI pipeline, further complicate my already complex CI configuration.
* They are not easy to customized: The maker of that tool must invent another configuration format.
* They are not easy to share: Dprint configuration can be shared via `"extends"`. This is not the case with a separate tool.
* They are not easy to make: One must write programmable code, as opposed to mere configuration.

So I beg you still to reconsider.

> there may be some disagreement about what the groups are

My definition of groups are mostly common naming convention used in JavaScript/TypeScript, I can hardly think of any other types of groups.

> some people might want to split up some of the groups into even more sub groups

Even if they do, I think adding another variant to `SortGroup` is trivial.

I also think that sorting by naming convention is pretty desirable. I can't be the only one who wants this.

**Comment by dsherret** [comment]
@KSXGitHub I'm changing this to "on hold", which just means I'll consider it in the future even though the issue is closed. This seems like one of those tasks that would be better letting sit for a while.

**Comment by KSXGitHub** [comment]
I just noticed that Rustfmt has this feature too (by default, the order is snake_case, TitleCase, UPPER_SNAKE_CASE). You may look at how Rustfmt does it for reference.
