### ISSUE TITLE
Parameters do not go to a single line when they possibly could

### ISSUE THREAD

**Issue by David-Else** [dprint/dprint-plugin-typescript#62]
**Describe the bug**

Does not work like the latest Prettier. Seems like a waste of screen space and less readable.

dprint-plugin-typescript version: deno 1.4.1

**Input Code (formatted by Deno)**

```ts
  constructor(
    position: Vector2,
  ) {
    this.position = position;
    this.keyboardInput = new KeyboardInputable();
  }
```

**Expected Output (formatted by Prettier)**

```ts
  constructor(position: Vector2) {
    this.position = position;
    this.keyboardInput = new KeyboardInputable();
  }
```

**Comment by dsherret** [comment]
This is as expected for now. Putting arguments back on a single line will be forced in a future version of deno once it's more stable.

For now, you can do this...

```ts
  constructor(position: Vector2,
  ) {
    this.position = position;
    this.keyboardInput = new KeyboardInputable();
  }
```

...then save and it will be the expected output.

**Comment by dsherret** [comment]
By the way, see here: https://dprint.dev/playground/#code/MYGwhgzhAEAqCmEAu0DeBYAUNawD2AdsgE4CuwSexAFFjjgA54QCWSLhAXNAGrwVUATABo60AJRoxOJAAsWEAHRNW7QtAC80FWw4EA3NOhyFigNbwAngCM8YYgBMAkgQakUWgvADu0ANJWtvbOru5g1iDw1OKG2NAAvljxQA/config/N4KABGBEAmCmB2B7SAuMAXATgV1gGnCgAcBDTEgW1nVkwGcA6IzWAM1oGUBLeAcwBtYAGR6xUGHLBABfEEA/language/typescript

Configuration that currently makes this collapse (but is not stable enough for Deno is):

```json
{
  "deno": true,
  "parameters.preferSingleLine": true
}
```

**Comment by David-Else** [comment]
Thanks for the fast feedback! I hope `preferSingleLine` becomes the default in Deno soon.

**Comment by dsherret** [comment]
Yeah, they want that 😅. I need to go through and get more edge cases to ensure it's stable before enabling it otherwise people will really complain.

I just updated it so import and export statements collapse to a single line (will be in the next release of Deno) and I think making this work for parameters could be next.
