### ISSUE TITLE
dprint moves `else` to the wrong `if`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [dprint/dprint-plugin-typescript#632]
**Describe the bug**

dprint-plugin-typescript version: x.x.x

**Input Code**

https://dprint.dev/playground/#code/JYMwFAhglA3qYCNYGMD2A7AzqgNgUwDodUBzMABigG4BfGvHTPAAngBMUNt8jSwBGavUZ4YaLLkLEyAJiFA/config/N4XyA/plugin/typescript

```ts
if(a){if(b){console.log(0);}}else if(d){console.log(1);}else{console.log(2);}
```

**Expected Output**

Something so that if `a` is `false` and `d` is `true` that code logs `1`

**Actual Output**

```ts
if (a) if (b) console.log(0);
else if (d) console.log(1);
else console.log(2);
```

which, when `a` is `false`, logs nothing.

**Comment by dsherret** [comment]
Thanks! That's pretty bad. Fixed in 0.90.5
