### ISSUE TITLE
Inline comments within parameters moved before previous comma

### ISSUE THREAD

**Issue by jakebailey** [dprint/dprint-plugin-typescript#650]
**Describe the bug**

dprint-plugin-typescript version: 0.91.3

**Input Code**

```ts
function foo(arg: number, /** @deferred */ cb: () => void): void {}

interface Foo {
  method<T>(
    arg: { new(...args: any[]): T }, // This is a comment
    arg2: (instance: T) => HTMLElement | undefined,
  ): Disposable;

  method2<T>(
    arg: { new(...args: any[]): T },
    arg2: (instance: T) => HTMLElement | undefined, // This is a comment
  ): Disposable;
}
```

**Expected Output**

```ts
function foo(arg: number, /** @deferred */ cb: () => void): void {}

interface Foo {
  method<T>(
    arg: { new(...args: any[]): T }, // This is a comment
    arg2: (instance: T) => HTMLElement | undefined,
  ): Disposable;

  method2<T>(
    arg: { new(...args: any[]): T },
    arg2: (instance: T) => HTMLElement | undefined, // This is a comment
  ): Disposable;
}
```

**Actual Output**

```ts
function foo(arg: number /** @deferred */, cb: () => void): void {}

interface Foo {
  method<T>(
    arg: { new(...args: any[]): T } // This is a comment
    ,
    arg2: (instance: T) => HTMLElement | undefined,
  ): Disposable;

  method2<T>(
    arg: { new(...args: any[]): T },
    arg2: (instance: T) => HTMLElement | undefined // This is a comment
    ,
  ): Disposable;
}
```

Noticed this when updating DT; 30 some files had instances of this.

This is particularly scary because https://github.com/microsoft/TypeScript/pull/58729 introduces a parameter JSDoc comment that shouldn't be moved around.

**Comment by jakebailey** [comment]
A bisect pointed to #630; maybe something in deno_ast?

**Comment by dsherret** [comment]
Not sure how we haven't got a report about this in Deno. It might be something that's only triggered with certain config. I'll take a look tomorrow.

**Comment by dsherret** [comment]
Opened https://github.com/swc-project/swc/issues/9290

Temporarily patched this in our wrapper: https://github.com/dprint/dprint-swc-ext/pull/62

**Comment by jakebailey** [comment]
Thank you once again!

**Comment by dsherret** [comment]
I opened https://github.com/dprint/dprint-plugin-typescript/issues/652 to catch this sooner in the future.
