### ISSUE TITLE
importDeclaration.spaceSurroundingNamedImports not working

### ISSUE THREAD

**Issue by simoncarbajal** [dprint/dprint-plugin-typescript#654]
**Describe the bug**
Running `dprint fmt` fails for `importDeclaration.spaceSurroundingNamedImports` rule

dprint-plugin-typescript version: 0.91.1

**Input Code**

```ts
import {getSignedUrl} from '@aws-sdk/s3-request-presigner'
```

**Expected Output**

```ts
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
```

**Actual Output**

```ts
import {getSignedUrl} from '@aws-sdk/s3-request-presigner'
```

As per documentation:
> true - Ex. `import { SomeExport, OtherExport } from "my-module";` (Default)

**Comment by dsherret** [comment]
I can't reproduce in the playground.

https://dprint.dev/playground/#code/JYWwDg9gTgLgBAbxgUwM4wL5wGZQiOAIhXUKA/config/N4KABGBECWC2AOB7ATgFwCIFMDGAbAhsvqtIgHYB0AzvPtpgMoCuyyiTZAJtGQOYBy+WJk4BJBClRVIALjCpkTTCAC+IIA/plugin/typescript

**Comment by SimonTweddle1** [comment]
Doesn't seem to follow the rules, for example **module.sortImportDeclarations**
https://dprint.dev/playground/#code/JYWwDg9gTgLgBAKjgQwM5wK4eAEzgMyghDgHItdSAoUSWOAbwHMBTGAZWCYDsWcBVKABsAvgSIlSAAWQB3VAFpUOANYB6VAGYFUFgEcMLVDAVhdqLryikgA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgEYA2ABgBpwoBXAZ0QBUBDAIxrzADNHo6KJIkAdwAyCRAGkEadjA6Q+UDAE8ADohoBjAE6wVGdqAj8pieBlSYc+AEwL+ARyoB7DIgDKy6IhndBjJTRuCADmXvKU-MwIjFpKAKIAHipa6jSwTvAAdE5qWowYTloACk5pGOnwMjSMALaIokjhRlAxWk6CAGJU8BrlGZm0iEUxptjq6jLJiByIWgByGd52UHQ1sADCTtAZbPiQjGlNRpAYebBw8MGbNTUHMkgAbrNHDs6uRW0quy00c4iIaABL2odAAQnkNBM9lMZvNFsDIDUnGgqF5MjRChgAJI1FSYgAiiA00Bi+Qq30RjAQGCplWWiORqMQ6MxiTxWgwhOJpL68Apt2ptIRiCSBKJJLyvJZHLmtQBbMx-NpNIQCNguLF3MlFWlGFldTQOPZGCVgtV9PVxq5ErJ-RoKkYkLcVC0bW6aBC+oBRsV7FOVEQlAAvgpIAArDGVfCGY6nKkXK5OG53PaPZ7B0MFGrQAwZyiQNBODQAa1mHHO3mjef4IuJVEB3wA2hEoAAqVsAengyMQAH0kSivGx6e2O62ALTbEuZCMZSCUAC6oZU0CowQQTZbkCwGAwX1wHY7K7XG8yaGS1LPiAeHeUak0Oj045ImQAnARMh+-DQagid3uaAPI9V3XPkzwvMwrxvWd4GfT9X0yABmTJv1-el-33Q9j1AmhwJ0SDARvLNoDgohMmsFCDjQrcMMArCQNPc98IwKCO0LEsywrODkIo1D5wgBcQCDEAgA/plugin/typescript

**Comment by dsherret** [comment]
That shows as sorting for me.

![image](https://github.com/user-attachments/assets/ccd3dea8-f8c4-4815-acc1-47d2eb48d650)

**Comment by SimonTweddle1** [comment]
it's sorting but my configuration is: **"module.sortImportDeclarations": "maintain"** so it shouldn't sort, right?
