### ISSUE TITLE
Allow vertical align union pipe prefix format

### ISSUE THREAD

**Issue by jasonkuhrt** [dprint/dprint-plugin-typescript#675]
Given this:

```ts
export type Input = boolean | {
  if?: boolean
  label?: string
  initialCount?: number
}
```

I would like:

```ts
export type Input =
  | boolean
  | {
      if?: boolean
      label?: string
      initialCount?: number
    }
```

There could be different heuristics for this:

1. I force a newline after `=` and the following is a union type (indicated I guess by if there are any other `|` present later in the line).
2. I force a `|` after an `=` and that forces the above formatting.

It seems idea (2) is simpler to implement and also perhaps a better expression of developer intent.

**Comment by Ilyat1337** [comment]
It already works. You need to add newline before or after `|`.
[Here is playground link ](https://dprint.dev/playground/#code/KYDwDg9gTgLgBDAnmYcCSA7MBXeBeOAIwggBtgBDDOAHwFgAoAb0bjgEsAzAfgC4iS5KqzikKhYKT5wAzjCjsMAcxGL2MdhVIBhCNgwxpGbAFsJURgF8gA/plugin/typescript)
