### ISSUE TITLE
build: Don't pin swc versions anymore

### ISSUE THREAD

**Issue by bartlomieju** [dprint/dprint-plugin-typescript#78]
Some time ago, we've pinned swc crates versions in `Cargo.toml` due to stability issues:

https://github.com/dprint/dprint-plugin-typescript/blob/6d540a5f9315c9e3f1dc19fd7f61279e783a79cd/Cargo.toml#L28-L29

Since that time swc got a lot more mature and there are not so many breaking changes these days.
I think it's high time we unpin those deps (remove `=` before version).

I've already done it in [`deno_doc`](https://github.com/denoland/deno_doc/pull/65) and [`deno_lint`](https://github.com/denoland/deno_lint/pull/552)

CC @dsherret @kdy1

**Comment by dsherret** [comment]
I agree and was thinking about this. There are also tests in swc for ranges now. It's been a long time since there were any regressions 😊

**Comment by kdy1** [comment]
I agree. I don't expect any breaking change without appropriate version bump according to semver.
