### ISSUE TITLE
Invalid output for JSX comment

### ISSUE THREAD

**Issue by thgh** [dprint/dprint-plugin-typescript#89]
**Describe the bug**

Comments in JSX tags are moved into the children when they don't appear on the same line as the component name.
dprint-plugin-typescript version: 0.38.3
Several cases: [playground](https://dprint.dev/playground/#code/GYVwdgxgLglg9mABAeQNYAoCUiDeAoRRAJwFMoQikAeANRhIHdEB6ZxCOAW05LCgMQA+KszqNBAbjwBfPHlCRYCFBmz5CpcpUS16TVuy48+A5pJlyF0eEgCSYAG4BDADYwAJllwDNFamKZTNg5uXn5CYVE9c1l5cGtlADk4KAAFEiJgEmgvdWIyPx0AxCDDUJNCMylYqyUkNFyfAu1dRhYAKjLjKER25gFIgJi4xRtEe2c3TzUmrX89EsrOkO7e-oiRIeqRhLtHVw9GjWb5ttNlozC1wejtnbrEZLSMrJyZ47mihfOuq76WGJAA/language/typescript)

[A different usecase](https://dprint.dev/playground/#code/GYVwdgxgLglg9mABAFQKYGcoAoCUiDeAUIogE6pQilIA8AJjAG4B8xJBb7iYIANr53YB6AFSIIcALaTUYKIhFDBAXzY0hDFgG5CqoA/language/typescript)

**Input Code**

```ts
function Test() {
  return <View
    // comment
  ></View>;
}
```

**Expected Output**

```ts
function Test() {
  return <View
    // comment
  />;
}
```

**Actual Output**

```ts
function Test() {
  return <View> // comment
  </View>;
}
```

**Comment by dsherret** [comment]
@thgh thanks for the great bug report!

**Comment by thgh** [comment]
Thanks for checking it out :-)
Should I make a new issue for [this one](https://dprint.dev/playground/#code/GYVwdgxgLglg9mABAFQKYGcoAoCUiDeAUIogE6pQilIA8AJjAG4B8xJBb7iYIANr53YB6AFSIIcALaTUYKIhFDBAXzY0hDFgG5CqoA/language/typescript)?

**Comment by dsherret** [comment]
I'll just reopen. Thanks for that other scenario :(
