### ISSUE TITLE
Missing space in JSX output

### ISSUE THREAD

**Issue by thgh** [dprint/dprint-plugin-typescript#90]
**Describe the bug**

dprint-plugin-typescript version: 0.38.3
[playground](https://dprint.dev/playground/#code/GYVwdgxgLglg9mABAcTnAJgCgJSIN4BQixiATgKZQilIA86MAbgHx7BoC++ARgIakdaAegYsA3AQ4ECoSLASIAQryy5CJMpWp1RzIhpJtOPflI3DdEqTPDR4SVBhz59xClRqJ6TPQcPs4DjwAckRgoL4BVy8RHysCIA/config/N4KAviQ/language/typescript)

**Input Code**

```ts
function Test() {
    return <div>
        {foo} {bar}
    </div>;
}
```

**Expected Output**

```ts
function Test() {
    return <div>
        {foo} {bar}
    </div>;
}
// or
function Test() {
    return <div>
        {foo}
        {' '}
        {bar}
    </div>;
}
```

**Actual Output** (the space must be compensated with `{' '}`

```ts
function Test() {
    return <div>
        {foo}
        {bar}
    </div>;
}
```

**Comment by dsherret** [comment]
This is #19. Closing, but I should really get on #19 now... I've also encountered this many times and it's an annoying bug.
