### ISSUE TITLE
cannot handle generics in with arrow functions

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#95]
**Describe the bug**

Deno version: 1.7.0 (master branch)

**Input Code**

```ts
const a = <T>(value: T): any => {};
```

**Expected Output**

No panics.

**Actual Output**

```
thread 'tokio-runtime-worker' panicked at 'Expected text `=`, but found `>`', [REDACTED]/.cargo/registry/src/github.com-1ecc6299db9ec823/dprint-plugin-typescript-0.38.5/src/parsing/parser_types.rs:132:13
```

**Comment by dsherret** [comment]
Problem here is that the span of the init expression doesn't include the type parameters in swc. Opened https://github.com/swc-project/swc/pull/1365

Just a note that this panic will only happen in debug mode to catch issues like this. Formats fine in release.
