### ISSUE TITLE
Check all top comments for ignore file comment

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-plugin-typescript#96]
As title.

**Comment by bartlomieju** [comment]
Code in `deno_lint` that handles that: https://github.com/denoland/deno_lint/blob/0cd33cec6392a80bf5693315630aece7232fc8d2/src/linter.rs#L358-L367

**Comment by dsherret** [comment]
Implemented what should be a very fast parser to skip these files: https://github.com/dprint/dprint-plugin-typescript/commit/4091af5f85bf17a3b66b4fd00b621f74fcd037ca#diff-c65b8237946e4f9fae4fff42b91c522fbbdbd31075ee610a18bc37cdaa9b58b5
