### ISSUE TITLE
mis-lexing of valid syntax causes panic in Deno

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#97]
**Describe the bug**

mis-lexing of valid syntax causes panic in Deno

Deno version: 1.7.1

**Input Code**

```ts
if (name === this.#DB[i].name) throw new Error(name);
```

**Expected Output**

No errors.

**Actual Output**

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\fmt_errors.rs:211:45

Ref: https://github.com/denoland/deno/issues/9392

**Comment by dsherret** [comment]
@kitsonk seems like a Deno error

**Comment by dsherret** [comment]
But then I wonder why this is resolved once converting the code to have braces. Seems to work in the dprint playground fine. I will look into it a bit.

**Comment by MierenManz** [comment]
If you make an extended class of Error and name that class `NameError` it does the same. But if you call the class `NameDuplicationError` it works fine without braces

**Comment by dsherret** [comment]
Yup, not a dprint-plugin-typescript panic. Closing. https://github.com/denoland/deno/issues/9392#issuecomment-772873546

@kitsonk FWIW, I always freak out when I read people having issues on discord and see "fmt" in the backtrace, but it's unrelated to `deno fmt` 😅
