### ISSUE TITLE
Formatting deletes code instead of erroring or leaving unmodified.

### ISSUE THREAD

**Issue by kitsonk** [dprint/dprint-plugin-typescript#99]
**Describe the bug**

Deno version: 1.7.2

**Input Code**

```ts
const Methods {
  f: (x, y) => x + y,
};

export default Methods;
```

**Expected Output**

An error or unmodified code.

**Actual Output**

```ts
const Methods;

export default Methods;
```

Ref: denoland/deno#9477

**Comment by dsherret** [comment]
Hmmm... probably due to swc becoming more relaxed (which is a good thing for swc, I was asking for it). I will look into it tomorrow (later today).

**Comment by dsherret** [comment]
Investigated. Opened https://github.com/swc-project/swc/issues/1391
